

from typing import Any, TYPE_CHECKING

from youdotcom.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .answercitation import AnswerCitation
    from .answerrequestbody import AnswerRequestBody
    from .answerresponse import AnswerResponse, AnswerResults
    from .answersearchresult import AnswerSearchResult
    from .contents import Contents, ContentsTypedDict
    from .contentsformats import ContentsFormats
    from .contentsmetadata import ContentsMetadata, ContentsMetadataTypedDict
    from .contentsop import (
        CONTENTS_OP_SERVERS,
        ContentsRequest,
        ContentsRequestTypedDict,
        ContentsResponse,
        ContentsResponseTypedDict,
    )
    from .country import Country
    from .finance_researchop import (
        FinanceResearchContentType,
        FinanceResearchDetail,
        FinanceResearchDetailTypedDict,
        FinanceResearchInput,
        FinanceResearchInputTypedDict,
        FinanceResearchInputUnion,
        FinanceResearchInputUnionTypedDict,
        FinanceResearchLoc,
        FinanceResearchLocTypedDict,
        FinanceResearchOutput,
        FinanceResearchOutputTypedDict,
        FinanceResearchRequest,
        FinanceResearchRequestTypedDict,
        FinanceResearchResponse,
        FinanceResearchResponseTypedDict,
        FinanceResearchSource,
        FinanceResearchSourceTypedDict,
    )
    from .financeresearcheffort import FinanceResearchEffort
    from .freshness import Freshness
    from .freshnessvalue import FreshnessValue, FreshnessValueTypedDict
    from .getresearchtaskop import (
        GetResearchTaskRequest,
        GetResearchTaskRequestTypedDict,
    )
    from .language import Language
    from .livecrawl import LiveCrawl
    from .livecrawlformats import LiveCrawlFormats
    from .newsresult import NewsResult, NewsResultTypedDict
    from .researcheffort import ResearchEffort
    from .researchop import (
        ResearchDetail,
        ResearchDetailTypedDict,
        ResearchInput,
        ResearchInputTypedDict,
        ResearchInputUnion,
        ResearchInputUnionTypedDict,
        ResearchLoc,
        ResearchLocTypedDict,
        ResearchRequest,
        ResearchRequestTypedDict,
        ResearchResult,
        ResearchResultTypedDict,
        SourceControl,
        SourceControlTypedDict,
    )
    from .researchresponse import (
        Content,
        ContentType,
        ContentTypedDict,
        Output,
        OutputTypedDict,
        ResearchResponse,
        ResearchResponseTypedDict,
        Source,
        SourceTypedDict,
    )
    from .researchtaskstreamevent import (
        Event,
        ResearchTaskStreamEvent,
        ResearchTaskStreamEventData,
        ResearchTaskStreamEventDataTypedDict,
        ResearchTaskStreamEventTypedDict,
    )
    from .safesearch import SafeSearch
    from .searchmetadata import SearchMetadata, SearchMetadataTypedDict
    from .searchop import SEARCH_OP_SERVERS, SearchRequest, SearchRequestTypedDict
    from .searchrequestbody import SearchRequestBody, SearchRequestBodyTypedDict
    from .searchresponse import (
        Results,
        ResultsTypedDict,
        SearchResponse,
        SearchResponseTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .streamresearchtaskop import (
        StreamResearchTaskRequest,
        StreamResearchTaskRequestTypedDict,
    )
    from .taskdetail import (
        Result,
        ResultTypedDict,
        TaskDetail,
        TaskDetailInput,
        TaskDetailInputTypedDict,
        TaskDetailStatus,
        TaskDetailTypedDict,
    )
    from .taskresponse import TaskResponse, TaskResponseStatus, TaskResponseTypedDict
    from .webresult import WebResult, WebResultTypedDict

__all__ = [
    "AnswerCitation",
    "AnswerRequestBody",
    "AnswerResponse",
    "AnswerResults",
    "AnswerSearchResult",
    "CONTENTS_OP_SERVERS",
    "Content",
    "ContentType",
    "ContentTypedDict",
    "Contents",
    "ContentsFormats",
    "ContentsMetadata",
    "ContentsMetadataTypedDict",
    "ContentsRequest",
    "ContentsRequestTypedDict",
    "ContentsResponse",
    "ContentsResponseTypedDict",
    "ContentsTypedDict",
    "Country",
    "Event",
    "FinanceResearchContentType",
    "FinanceResearchDetail",
    "FinanceResearchDetailTypedDict",
    "FinanceResearchEffort",
    "FinanceResearchInput",
    "FinanceResearchInputTypedDict",
    "FinanceResearchInputUnion",
    "FinanceResearchInputUnionTypedDict",
    "FinanceResearchLoc",
    "FinanceResearchLocTypedDict",
    "FinanceResearchOutput",
    "FinanceResearchOutputTypedDict",
    "FinanceResearchRequest",
    "FinanceResearchRequestTypedDict",
    "FinanceResearchResponse",
    "FinanceResearchResponseTypedDict",
    "FinanceResearchSource",
    "FinanceResearchSourceTypedDict",
    "Freshness",
    "FreshnessValue",
    "FreshnessValueTypedDict",
    "GetResearchTaskRequest",
    "GetResearchTaskRequestTypedDict",
    "Language",
    "LiveCrawl",
    "LiveCrawlFormats",
    "NewsResult",
    "NewsResultTypedDict",
    "Output",
    "OutputTypedDict",
    "ResearchDetail",
    "ResearchDetailTypedDict",
    "ResearchEffort",
    "ResearchInput",
    "ResearchInputTypedDict",
    "ResearchInputUnion",
    "ResearchInputUnionTypedDict",
    "ResearchLoc",
    "ResearchLocTypedDict",
    "ResearchRequest",
    "ResearchRequestTypedDict",
    "ResearchResponse",
    "ResearchResult",
    "ResearchResultTypedDict",
    "ResearchResponseTypedDict",
    "ResearchTaskStreamEvent",
    "ResearchTaskStreamEventData",
    "ResearchTaskStreamEventDataTypedDict",
    "ResearchTaskStreamEventTypedDict",
    "Result",
    "ResultTypedDict",
    "Results",
    "ResultsTypedDict",
    "SEARCH_OP_SERVERS",
    "SafeSearch",
    "SearchMetadata",
    "SearchMetadataTypedDict",
    "SearchRequest",
    "SearchRequestBody",
    "SearchRequestBodyTypedDict",
    "SearchRequestTypedDict",
    "SearchResponse",
    "SearchResponseTypedDict",
    "Security",
    "SecurityTypedDict",
    "Source",
    "SourceControl",
    "SourceControlTypedDict",
    "SourceTypedDict",
    "StreamResearchTaskRequest",
    "StreamResearchTaskRequestTypedDict",
    "TaskDetail",
    "TaskDetailInput",
    "TaskDetailInputTypedDict",
    "TaskDetailStatus",
    "TaskDetailTypedDict",
    "TaskResponse",
    "TaskResponseStatus",
    "TaskResponseTypedDict",
    "WebResult",
    "WebResultTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AnswerCitation": ".answercitation",
    "AnswerRequestBody": ".answerrequestbody",
    "AnswerResponse": ".answerresponse",
    "AnswerResults": ".answerresponse",
    "AnswerSearchResult": ".answersearchresult",
    "Contents": ".contents",
    "ContentsTypedDict": ".contents",
    "ContentsFormats": ".contentsformats",
    "ContentsMetadata": ".contentsmetadata",
    "ContentsMetadataTypedDict": ".contentsmetadata",
    "CONTENTS_OP_SERVERS": ".contentsop",
    "ContentsRequest": ".contentsop",
    "ContentsRequestTypedDict": ".contentsop",
    "ContentsResponse": ".contentsop",
    "ContentsResponseTypedDict": ".contentsop",
    "Country": ".country",
    "FinanceResearchContentType": ".finance_researchop",
    "FinanceResearchDetail": ".finance_researchop",
    "FinanceResearchDetailTypedDict": ".finance_researchop",
    "FinanceResearchInput": ".finance_researchop",
    "FinanceResearchInputTypedDict": ".finance_researchop",
    "FinanceResearchInputUnion": ".finance_researchop",
    "FinanceResearchInputUnionTypedDict": ".finance_researchop",
    "FinanceResearchLoc": ".finance_researchop",
    "FinanceResearchLocTypedDict": ".finance_researchop",
    "FinanceResearchOutput": ".finance_researchop",
    "FinanceResearchOutputTypedDict": ".finance_researchop",
    "FinanceResearchRequest": ".finance_researchop",
    "FinanceResearchRequestTypedDict": ".finance_researchop",
    "FinanceResearchResponse": ".finance_researchop",
    "FinanceResearchResponseTypedDict": ".finance_researchop",
    "FinanceResearchSource": ".finance_researchop",
    "FinanceResearchSourceTypedDict": ".finance_researchop",
    "FinanceResearchEffort": ".financeresearcheffort",
    "Freshness": ".freshness",
    "FreshnessValue": ".freshnessvalue",
    "FreshnessValueTypedDict": ".freshnessvalue",
    "GetResearchTaskRequest": ".getresearchtaskop",
    "GetResearchTaskRequestTypedDict": ".getresearchtaskop",
    "Language": ".language",
    "LiveCrawl": ".livecrawl",
    "LiveCrawlFormats": ".livecrawlformats",
    "NewsResult": ".newsresult",
    "NewsResultTypedDict": ".newsresult",
    "ResearchEffort": ".researcheffort",
    "ResearchDetail": ".researchop",
    "ResearchDetailTypedDict": ".researchop",
    "ResearchInput": ".researchop",
    "ResearchInputTypedDict": ".researchop",
    "ResearchInputUnion": ".researchop",
    "ResearchInputUnionTypedDict": ".researchop",
    "ResearchLoc": ".researchop",
    "ResearchLocTypedDict": ".researchop",
    "ResearchRequest": ".researchop",
    "ResearchRequestTypedDict": ".researchop",
    "ResearchResult": ".researchop",
    "ResearchResultTypedDict": ".researchop",
    "SourceControl": ".researchop",
    "SourceControlTypedDict": ".researchop",
    "Content": ".researchresponse",
    "ContentType": ".researchresponse",
    "ContentTypedDict": ".researchresponse",
    "Output": ".researchresponse",
    "OutputTypedDict": ".researchresponse",
    "ResearchResponse": ".researchresponse",
    "ResearchResponseTypedDict": ".researchresponse",
    "Source": ".researchresponse",
    "SourceTypedDict": ".researchresponse",
    "Event": ".researchtaskstreamevent",
    "ResearchTaskStreamEvent": ".researchtaskstreamevent",
    "ResearchTaskStreamEventData": ".researchtaskstreamevent",
    "ResearchTaskStreamEventDataTypedDict": ".researchtaskstreamevent",
    "ResearchTaskStreamEventTypedDict": ".researchtaskstreamevent",
    "SafeSearch": ".safesearch",
    "SearchMetadata": ".searchmetadata",
    "SearchMetadataTypedDict": ".searchmetadata",
    "SEARCH_OP_SERVERS": ".searchop",
    "SearchRequest": ".searchop",
    "SearchRequestTypedDict": ".searchop",
    "SearchRequestBody": ".searchrequestbody",
    "SearchRequestBodyTypedDict": ".searchrequestbody",
    "Results": ".searchresponse",
    "ResultsTypedDict": ".searchresponse",
    "SearchResponse": ".searchresponse",
    "SearchResponseTypedDict": ".searchresponse",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "StreamResearchTaskRequest": ".streamresearchtaskop",
    "StreamResearchTaskRequestTypedDict": ".streamresearchtaskop",
    "TaskDetail": ".taskdetail",
    "TaskDetailInput": ".taskdetail",
    "TaskDetailInputTypedDict": ".taskdetail",
    "TaskDetailStatus": ".taskdetail",
    "TaskDetailTypedDict": ".taskdetail",
    "Result": ".taskdetail",
    "ResultTypedDict": ".taskdetail",
    "TaskResponse": ".taskresponse",
    "TaskResponseStatus": ".taskresponse",
    "TaskResponseTypedDict": ".taskresponse",
    "WebResult": ".webresult",
    "WebResultTypedDict": ".webresult",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
