"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


AgentType = Literal[
    "express",
    "advanced",
]
r"""Built-in agent types"""
