"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .advancedagentrunsrequest import (
    AdvancedAgentRunsRequest,
    AdvancedAgentRunsRequestTypedDict,
)
from .agentrunsbatchresponse import (
    AgentRunsBatchResponse,
    AgentRunsBatchResponseTypedDict,
)
from .agentrunsstreamingresponse import (
    AgentRunsStreamingResponse,
    AgentRunsStreamingResponseTypedDict,
)
from .customagentrunsrequest import (
    CustomAgentRunsRequest,
    CustomAgentRunsRequestTypedDict,
)
from .expressagentrunsrequest import (
    ExpressAgentRunsRequest,
    ExpressAgentRunsRequestTypedDict,
)
from typing import Union
from typing_extensions import TypeAliasType
from youdotcom.utils import eventstreaming


AGENTS_RUNS_OP_SERVERS = [
    "https://api.you.com",
]


AgentsRunsRequestTypedDict = TypeAliasType(
    "AgentsRunsRequestTypedDict",
    Union[
        CustomAgentRunsRequestTypedDict,
        ExpressAgentRunsRequestTypedDict,
        AdvancedAgentRunsRequestTypedDict,
    ],
)
r"""The parameters to ask the agent a question"""


AgentsRunsRequest = TypeAliasType(
    "AgentsRunsRequest",
    Union[CustomAgentRunsRequest, ExpressAgentRunsRequest, AdvancedAgentRunsRequest],
)
r"""The parameters to ask the agent a question"""


AgentsRunsResponseTypedDict = TypeAliasType(
    "AgentsRunsResponseTypedDict",
    Union[
        AgentRunsBatchResponseTypedDict,
        Union[
            eventstreaming.EventStream[AgentRunsStreamingResponseTypedDict],
            eventstreaming.EventStreamAsync[AgentRunsStreamingResponseTypedDict],
        ],
    ],
)


AgentsRunsResponse = TypeAliasType(
    "AgentsRunsResponse",
    Union[
        AgentRunsBatchResponse,
        Union[
            eventstreaming.EventStream[AgentRunsStreamingResponse],
            eventstreaming.EventStreamAsync[AgentRunsStreamingResponse],
        ],
    ],
)
