"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .response_created import ResponseCreated, ResponseCreatedTypedDict
from .response_done import ResponseDone, ResponseDoneTypedDict
from .response_output_content_full import (
    ResponseOutputContentFull,
    ResponseOutputContentFullTypedDict,
)
from .response_output_item_added import (
    ResponseOutputItemAdded,
    ResponseOutputItemAddedTypedDict,
)
from .response_output_item_done import (
    ResponseOutputItemDone,
    ResponseOutputItemDoneTypedDict,
)
from .response_output_text_delta import (
    ResponseOutputTextDelta,
    ResponseOutputTextDeltaTypedDict,
)
from .response_starting import ResponseStarting, ResponseStartingTypedDict
from pydantic import Field
from typing import Union
from typing_extensions import Annotated, TypeAliasType, TypedDict
from youdotcom.types import BaseModel


DataTypedDict = TypeAliasType(
    "DataTypedDict",
    Union[
        ResponseCreatedTypedDict,
        ResponseStartingTypedDict,
        ResponseOutputItemAddedTypedDict,
        ResponseOutputContentFullTypedDict,
        ResponseOutputItemDoneTypedDict,
        ResponseOutputTextDeltaTypedDict,
        ResponseDoneTypedDict,
    ],
)


Data = Annotated[
    Union[
        ResponseCreated,
        ResponseStarting,
        ResponseOutputItemAdded,
        ResponseOutputContentFull,
        ResponseOutputItemDone,
        ResponseOutputTextDelta,
        ResponseDone,
    ],
    Field(discriminator="TYPE"),
]


class AgentRunsStreamingResponseTypedDict(TypedDict):
    r"""A server-sent event containing stock market update content"""

    id: str
    r"""Sequence number of the SSE event, starts from 0"""
    event: str
    r"""The type of the SSE event"""
    data: DataTypedDict


class AgentRunsStreamingResponse(BaseModel):
    r"""A server-sent event containing stock market update content"""

    id: str
    r"""Sequence number of the SSE event, starts from 0"""

    event: str
    r"""The type of the SSE event"""

    data: Data
