"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import List, Union
from typing_extensions import TypeAliasType, TypedDict
from youdotcom.types import BaseModel


LocTypedDict = TypeAliasType("LocTypedDict", Union[str, int])


Loc = TypeAliasType("Loc", Union[str, int])


class DetailTypedDict(TypedDict):
    type: str
    loc: List[LocTypedDict]
    msg: str
    input: str


class Detail(BaseModel):
    type: str

    loc: List[Loc]

    msg: str

    input: str
