"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class AgentRunsResponseWebSearchResultTypedDict(TypedDict):
    r"""The text response of the agent. This field only returns when the type is `web_search.results`"""

    citation_uri: str
    r"""The web search result the agent returned along in its response"""
    title: str
    r"""The title of the web site returned under url"""
    snippet: str
    r"""A textual portion of the web site returned under url"""
    url: str
    r"""The web search result the agent returned along in its response"""
    source_type: Literal["web_search"]
    r"""The type of content the agent can return outside a text response"""
    provider: NotRequired[str]
    r"""This is currently unused"""
    thumbnail_url: NotRequired[str]
    r"""The thumbnail image of the url"""


class AgentRunsResponseWebSearchResult(BaseModel):
    r"""The text response of the agent. This field only returns when the type is `web_search.results`"""

    citation_uri: str
    r"""The web search result the agent returned along in its response"""

    title: str
    r"""The title of the web site returned under url"""

    snippet: str
    r"""A textual portion of the web site returned under url"""

    url: str
    r"""The web search result the agent returned along in its response"""

    SOURCE_TYPE: Annotated[
        Annotated[Literal["web_search"], AfterValidator(validate_const("web_search"))],
        pydantic.Field(alias="source_type"),
    ] = "web_search"
    r"""The type of content the agent can return outside a text response"""

    provider: Optional[str] = None
    r"""This is currently unused"""

    thumbnail_url: Optional[str] = None
    r"""The thumbnail image of the url"""
