"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ComputeToolTypedDict(TypedDict):
    type: Literal["compute"]
    r"""Setting this value to \"compute\" is mandatory to use the compute agent."""


class ComputeTool(BaseModel):
    TYPE: Annotated[
        Annotated[Literal["compute"], AfterValidator(validate_const("compute"))],
        pydantic.Field(alias="type"),
    ] = "compute"
    r"""Setting this value to \"compute\" is mandatory to use the compute agent."""
