"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contentsformat import ContentsFormat
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


class ContentsRequestTypedDict(TypedDict):
    urls: NotRequired[List[str]]
    r"""Array of URLs to fetch the contents from."""
    format_: NotRequired[ContentsFormat]
    r"""The format of the content to be returned."""


class ContentsRequest(BaseModel):
    urls: Optional[List[str]] = None
    r"""Array of URLs to fetch the contents from."""

    format_: Annotated[Optional[ContentsFormat], pydantic.Field(alias="format")] = None
    r"""The format of the content to be returned."""


class ContentsMetadataTypedDict(TypedDict):
    site_name: NotRequired[str]
    r"""The OpenGraph site name of the web page."""
    favicon_url: NotRequired[str]
    r"""The URL of the favicon of the web page's domain."""


class ContentsMetadata(BaseModel):
    site_name: Optional[str] = None
    r"""The OpenGraph site name of the web page."""

    favicon_url: Optional[str] = None
    r"""The URL of the favicon of the web page's domain."""


class ContentsResponseTypedDict(TypedDict):
    url: NotRequired[str]
    r"""The webpage URL whose content has been fetched."""
    title: NotRequired[str]
    r"""The title of the web page."""
    html: NotRequired[Nullable[str]]
    r"""The retrieved HTML content of the web page."""
    markdown: NotRequired[Nullable[str]]
    r"""The retrieved Markdown content of the web page."""
    metadata: NotRequired[ContentsMetadataTypedDict]


class ContentsResponse(BaseModel):
    url: Optional[str] = None
    r"""The webpage URL whose content has been fetched."""

    title: Optional[str] = None
    r"""The title of the web page."""

    html: OptionalNullable[str] = UNSET
    r"""The retrieved HTML content of the web page."""

    markdown: OptionalNullable[str] = UNSET
    r"""The retrieved Markdown content of the web page."""

    metadata: Optional[ContentsMetadata] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["url", "title", "html", "markdown", "metadata"]
        nullable_fields = ["html", "markdown"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
