"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class ContentsTypedDict(TypedDict):
    r"""Contents of the page if livecrawl was enabled."""

    html: NotRequired[str]
    r"""The HTML content of the page."""
    markdown: NotRequired[str]
    r"""The Markdown content of the page."""


class Contents(BaseModel):
    r"""Contents of the page if livecrawl was enabled."""

    html: Optional[str] = None
    r"""The HTML content of the page."""

    markdown: Optional[str] = None
    r"""The Markdown content of the page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["html", "markdown"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
