"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .contentsformatsitems import ContentsFormatsItems
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL
from youdotcom.utils import FieldMetadata, HeaderMetadata, RequestMetadata


CONTENTS_OP_SERVERS = [
    "https://ydc-index.io",
]


class ContentsRequestBodyTypedDict(TypedDict):
    urls: NotRequired[List[str]]
    r"""Array of URLs to fetch the contents from."""
    formats: NotRequired[List[ContentsFormatsItems]]
    r"""Array of content formats to return. All included formats are returned in the response. Include \"metadata\" to get JSON-LD and OpenGraph information, if available."""
    crawl_timeout: NotRequired[int]
    r"""Maximum time in seconds to wait for page content. Must be between 1 and 60 seconds. Default is 10 seconds."""


class ContentsRequestBody(BaseModel):
    urls: Optional[List[str]] = None
    r"""Array of URLs to fetch the contents from."""

    formats: Optional[List[ContentsFormatsItems]] = None
    r"""Array of content formats to return. All included formats are returned in the response. Include \"metadata\" to get JSON-LD and OpenGraph information, if available."""

    crawl_timeout: Optional[int] = 10
    r"""Maximum time in seconds to wait for page content. Must be between 1 and 60 seconds. Default is 10 seconds."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["urls", "formats", "crawl_timeout"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ContentsRequestTypedDict(TypedDict):
    x_api_key: str
    r"""A unique API Key is required to authorize API access. [Get your API Key with free credits](https://you.com/platform)."""
    body: NotRequired[ContentsRequestBodyTypedDict]


class ContentsRequest(BaseModel):
    x_api_key: Annotated[
        str,
        pydantic.Field(alias="X-API-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""A unique API Key is required to authorize API access. [Get your API Key with free credits](https://you.com/platform)."""

    body: Annotated[
        Optional[ContentsRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
