"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class CustomAgentRunsRequestTypedDict(TypedDict):
    agent: str
    r"""Set the value to a Custom Agent's ID. Learn how to obtain an agent ID here [Create Custom Agents](https://docs.you.com/agents/custom/create-agents)."""
    input: str
    r"""The question you'd like to ask the agent"""
    stream: NotRequired[bool]
    r"""Must be set to `true` when you want to stream the agent response as it's being generated, and `false` when you want the response to return after the agent has finished."""


class CustomAgentRunsRequest(BaseModel):
    agent: str
    r"""Set the value to a Custom Agent's ID. Learn how to obtain an agent ID here [Create Custom Agents](https://docs.you.com/agents/custom/create-agents)."""

    input: str
    r"""The question you'd like to ask the agent"""

    stream: Optional[bool] = False
    r"""Must be set to `true` when you want to stream the agent response as it's being generated, and `false` when you want the response to return after the agent has finished."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["stream"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
