"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel


class CustomAgentRunsRequestTypedDict(TypedDict):
    agent: str
    r"""Set the value to a Custom Agent's ID. Learn how to obtain an agent ID here [Create Custom Agents](/agents/custom/create-agents)."""
    input: str
    r"""The question you'd like to ask the agent"""
    stream: NotRequired[bool]
    r"""Must be set to `true` when you want to stream the agent response as it's being generated, and `false` when you want the response to return after the agent has finished."""


class CustomAgentRunsRequest(BaseModel):
    agent: str
    r"""Set the value to a Custom Agent's ID. Learn how to obtain an agent ID here [Create Custom Agents](/agents/custom/create-agents)."""

    input: str
    r"""The question you'd like to ask the agent"""

    stream: Optional[bool] = False
    r"""Must be set to `true` when you want to stream the agent response as it's being generated, and `false` when you want the response to return after the agent has finished."""
