"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ExpressAgentRunsRequestToolTypedDict(TypedDict):
    type: Literal["web_search"]
    r"""Setting this value to \"web_search\" is mandatory to use the web_search tool."""


class ExpressAgentRunsRequestTool(BaseModel):
    TYPE: Annotated[
        Annotated[Literal["web_search"], AfterValidator(validate_const("web_search"))],
        pydantic.Field(alias="type"),
    ] = "web_search"
    r"""Setting this value to \"web_search\" is mandatory to use the web_search tool."""


class ExpressAgentRunsRequestTypedDict(TypedDict):
    input: str
    r"""The question you'd like to ask the agent"""
    agent: Literal["express"]
    r"""Setting this value to \"express\" is mandatory to use the express agent."""
    stream: NotRequired[bool]
    r"""Must be set to `true` when you want to stream the express agent response as it's being generated, and `false` when you want the response to return after the agent has finished."""
    tools: NotRequired[List[ExpressAgentRunsRequestToolTypedDict]]
    r"""You can optionally ground the express agent response using results fetched from the web (max 1 web search)"""


class ExpressAgentRunsRequest(BaseModel):
    input: str
    r"""The question you'd like to ask the agent"""

    AGENT: Annotated[
        Annotated[Literal["express"], AfterValidator(validate_const("express"))],
        pydantic.Field(alias="agent"),
    ] = "express"
    r"""Setting this value to \"express\" is mandatory to use the express agent."""

    stream: Optional[bool] = False
    r"""Must be set to `true` when you want to stream the express agent response as it's being generated, and `false` when you want the response to return after the agent has finished."""

    tools: Optional[List[ExpressAgentRunsRequestTool]] = None
    r"""You can optionally ground the express agent response using results fetched from the web (max 1 web search)"""
