"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .country import Country
from .freshness import Freshness
from .livecrawl import LiveCrawl
from .livecrawlformats import LiveCrawlFormats
from .safesearch import SafeSearch
from datetime import datetime
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import FieldMetadata, QueryParamMetadata


GetV1SearchFreshnessTypedDict = TypeAliasType(
    "GetV1SearchFreshnessTypedDict", Union[Freshness, str]
)
r"""Specifies the freshness of the results to return."""


GetV1SearchFreshness = TypeAliasType("GetV1SearchFreshness", Union[Freshness, str])
r"""Specifies the freshness of the results to return."""


GetV1SearchCountryTypedDict = TypeAliasType(
    "GetV1SearchCountryTypedDict", Union[Country, str]
)
r"""The country code that determines the geographical focus of the web results."""


GetV1SearchCountry = TypeAliasType("GetV1SearchCountry", Union[Country, str])
r"""The country code that determines the geographical focus of the web results."""


GetV1SearchSafesearchTypedDict = TypeAliasType(
    "GetV1SearchSafesearchTypedDict", Union[SafeSearch, str]
)
r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""


GetV1SearchSafesearch = TypeAliasType("GetV1SearchSafesearch", Union[SafeSearch, str])
r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""


GetV1SearchLivecrawlTypedDict = TypeAliasType(
    "GetV1SearchLivecrawlTypedDict", Union[LiveCrawl, str]
)
r"""Indicates which section(s) of search results to livecrawl and return full page content."""


GetV1SearchLivecrawl = TypeAliasType("GetV1SearchLivecrawl", Union[LiveCrawl, str])
r"""Indicates which section(s) of search results to livecrawl and return full page content."""


GetV1SearchLivecrawlFormatsTypedDict = TypeAliasType(
    "GetV1SearchLivecrawlFormatsTypedDict", Union[LiveCrawlFormats, str]
)
r"""Indicates the format of the livecrawled content."""


GetV1SearchLivecrawlFormats = TypeAliasType(
    "GetV1SearchLivecrawlFormats", Union[LiveCrawlFormats, str]
)
r"""Indicates the format of the livecrawled content."""


class GetV1SearchRequestTypedDict(TypedDict):
    query: str
    r"""The search query used to retrieve relevant results from the web. You can also include [search operators](#search-operators) to refine your search."""
    count: NotRequired[int]
    r"""Specifies the maximum number of search results to return per section (the sections are `web` and `news`. See the JSON response to visualize them)."""
    freshness: NotRequired[GetV1SearchFreshnessTypedDict]
    r"""Specifies the freshness of the results to return."""
    offset: NotRequired[int]
    r"""Indicates the `offset` for pagination. The `offset` is calculated in multiples of `count`. For example, if `count = 5` and `offset = 1`, results 5–10 will be returned. Range `0 ≤ offset ≤ 9`."""
    country: NotRequired[GetV1SearchCountryTypedDict]
    r"""The country code that determines the geographical focus of the web results."""
    safesearch: NotRequired[GetV1SearchSafesearchTypedDict]
    r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""
    livecrawl: NotRequired[GetV1SearchLivecrawlTypedDict]
    r"""Indicates which section(s) of search results to livecrawl and return full page content."""
    livecrawl_formats: NotRequired[GetV1SearchLivecrawlFormatsTypedDict]
    r"""Indicates the format of the livecrawled content."""


class GetV1SearchRequest(BaseModel):
    query: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ] = "Your query"
    r"""The search query used to retrieve relevant results from the web. You can also include [search operators](#search-operators) to refine your search."""

    count: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the maximum number of search results to return per section (the sections are `web` and `news`. See the JSON response to visualize them)."""

    freshness: Annotated[
        Optional[GetV1SearchFreshness],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the freshness of the results to return."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Indicates the `offset` for pagination. The `offset` is calculated in multiples of `count`. For example, if `count = 5` and `offset = 1`, results 5–10 will be returned. Range `0 ≤ offset ≤ 9`."""

    country: Annotated[
        Optional[GetV1SearchCountry],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The country code that determines the geographical focus of the web results."""

    safesearch: Annotated[
        Optional[GetV1SearchSafesearch],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""

    livecrawl: Annotated[
        Optional[GetV1SearchLivecrawl],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Indicates which section(s) of search results to livecrawl and return full page content."""

    livecrawl_formats: Annotated[
        Optional[GetV1SearchLivecrawlFormats],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Indicates the format of the livecrawled content."""


class WebTypedDict(TypedDict):
    url: NotRequired[str]
    r"""The URL of the specific search result."""
    title: NotRequired[str]
    r"""The title or name of the search result."""
    description: NotRequired[str]
    r"""A brief description of the content of the search result."""
    snippets: NotRequired[List[str]]
    r"""An array of text snippets from the search result, providing a preview of the content."""
    thumbnail_url: NotRequired[str]
    r"""URL of the thumbnail."""
    page_age: NotRequired[datetime]
    r"""The age of the search result."""
    authors: NotRequired[List[str]]
    r"""An array of authors of the search result."""
    favicon_url: NotRequired[str]
    r"""The URL of the favicon of the search result's domain."""


class Web(BaseModel):
    url: Optional[str] = None
    r"""The URL of the specific search result."""

    title: Optional[str] = None
    r"""The title or name of the search result."""

    description: Optional[str] = None
    r"""A brief description of the content of the search result."""

    snippets: Optional[List[str]] = None
    r"""An array of text snippets from the search result, providing a preview of the content."""

    thumbnail_url: Optional[str] = None
    r"""URL of the thumbnail."""

    page_age: Optional[datetime] = None
    r"""The age of the search result."""

    authors: Optional[List[str]] = None
    r"""An array of authors of the search result."""

    favicon_url: Optional[str] = None
    r"""The URL of the favicon of the search result's domain."""


class NewsTypedDict(TypedDict):
    title: NotRequired[str]
    r"""The title of the news result."""
    description: NotRequired[str]
    r"""A brief description of the content of the news result."""
    page_age: NotRequired[datetime]
    r"""UTC timestamp of the article's publication date."""
    thumbnail_url: NotRequired[str]
    r"""URL of the thumbnail."""
    url: NotRequired[str]
    r"""The URL of the news result."""


class News(BaseModel):
    title: Optional[str] = None
    r"""The title of the news result."""

    description: Optional[str] = None
    r"""A brief description of the content of the news result."""

    page_age: Optional[datetime] = None
    r"""UTC timestamp of the article's publication date."""

    thumbnail_url: Optional[str] = None
    r"""URL of the thumbnail."""

    url: Optional[str] = None
    r"""The URL of the news result."""


class ResultsTypedDict(TypedDict):
    web: NotRequired[List[WebTypedDict]]
    news: NotRequired[List[NewsTypedDict]]


class Results(BaseModel):
    web: Optional[List[Web]] = None

    news: Optional[List[News]] = None


class MetadataTypedDict(TypedDict):
    request_uuid: NotRequired[str]
    query: NotRequired[str]
    r"""Returns the search query used to retrieve the results."""
    latency: NotRequired[float]


class Metadata(BaseModel):
    request_uuid: Optional[str] = None

    query: Optional[str] = None
    r"""Returns the search query used to retrieve the results."""

    latency: Optional[float] = None


class GetV1SearchResponseTypedDict(TypedDict):
    r"""A JSON object containing unified search results from web and news sources"""

    results: NotRequired[ResultsTypedDict]
    metadata: NotRequired[MetadataTypedDict]


class GetV1SearchResponse(BaseModel):
    r"""A JSON object containing unified search results from web and news sources"""

    results: Optional[Results] = None

    metadata: Optional[Metadata] = None
