"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class LiveCrawlFormats(str, Enum):
    r"""Indicates the format of the livecrawled content."""

    HTML = "html"
    MARKDOWN = "markdown"
