"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agenttype import AgentType
from .fullresponse import FullResponse, FullResponseTypedDict
from .tool import Tool, ToolTypedDict
from .verbosity import Verbosity
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import eventstreaming


POST_V1_AGENTS_RUNS_OP_SERVERS = [
    "https://api.you.com",
]


AgentTypedDict = TypeAliasType("AgentTypedDict", Union[AgentType, str])
r"""Agent type (express, advanced) or custom agent UUID"""


Agent = TypeAliasType("Agent", Union[AgentType, str])
r"""Agent type (express, advanced) or custom agent UUID"""


class WorkflowConfigTypedDict(TypedDict):
    max_workflow_steps: NotRequired[int]
    r"""Maximum number of workflow steps"""


class WorkflowConfig(BaseModel):
    max_workflow_steps: Optional[int] = 5
    r"""Maximum number of workflow steps"""


class PostV1AgentsRunsRequestTypedDict(TypedDict):
    agent: AgentTypedDict
    r"""Agent type (express, advanced) or custom agent UUID"""
    input: str
    r"""User input prompt."""
    stream: NotRequired[bool]
    tools: NotRequired[List[ToolTypedDict]]
    r"""Array of tool configurations"""
    verbosity: NotRequired[Verbosity]
    r"""Response verbosity level"""
    workflow_config: NotRequired[WorkflowConfigTypedDict]


class PostV1AgentsRunsRequest(BaseModel):
    agent: Agent
    r"""Agent type (express, advanced) or custom agent UUID"""

    input: str
    r"""User input prompt."""

    stream: Optional[bool] = False

    tools: Optional[List[Tool]] = None
    r"""Array of tool configurations"""

    verbosity: Optional[Verbosity] = None
    r"""Response verbosity level"""

    workflow_config: Optional[WorkflowConfig] = None


class ForbiddenErrorTypedDict(TypedDict):
    status: str
    code: str
    title: str
    detail: str


class ForbiddenError(BaseModel):
    status: str

    code: str

    title: str

    detail: str


class UnauthorizedErrorTypedDict(TypedDict):
    status: str
    code: str
    title: str
    detail: str


class UnauthorizedError(BaseModel):
    status: str

    code: str

    title: str

    detail: str


class BadRequestErrorTypedDict(TypedDict):
    status: str
    code: str
    title: str
    detail: str


class BadRequestError(BaseModel):
    status: str

    code: str

    title: str

    detail: str


class ResponseTypedDict(TypedDict):
    type: NotRequired[str]
    r"""The type of the response."""
    output_index: NotRequired[int]
    r"""The index of the output in the response."""
    delta: NotRequired[str]
    r"""The delta of the response."""
    full: NotRequired[FullResponseTypedDict]


class Response(BaseModel):
    type: Optional[str] = None
    r"""The type of the response."""

    output_index: Optional[int] = None
    r"""The index of the output in the response."""

    delta: Optional[str] = None
    r"""The delta of the response."""

    full: Optional[FullResponse] = None


class DataTypedDict(TypedDict):
    seq_id: NotRequired[int]
    r"""Sequence number of the SSE event, starts from 0. Same as `id` field."""
    type: NotRequired[str]
    r"""The type of the SSE event. Same as `event` field."""
    response: NotRequired[ResponseTypedDict]


class Data(BaseModel):
    seq_id: Optional[int] = None
    r"""Sequence number of the SSE event, starts from 0. Same as `id` field."""

    type: Optional[str] = None
    r"""The type of the SSE event. Same as `event` field."""

    response: Optional[Response] = None


class PostV1AgentsRunsEventStreamResponseBodyTypedDict(TypedDict):
    r"""Inference response in application/json or text/event-stream format."""

    id: NotRequired[str]
    r"""Sequence number of the SSE event"""
    event: NotRequired[str]
    r"""The type of the SSE event."""
    data: NotRequired[DataTypedDict]


class PostV1AgentsRunsEventStreamResponseBody(BaseModel):
    r"""Inference response in application/json or text/event-stream format."""

    id: Optional[str] = None
    r"""Sequence number of the SSE event"""

    event: Optional[str] = None
    r"""The type of the SSE event."""

    data: Optional[Data] = None


class ContentTypedDict(TypedDict):
    pass


class Content(BaseModel):
    pass


ContentUnion1TypedDict = TypeAliasType(
    "ContentUnion1TypedDict", Union[ContentTypedDict, List[Any]]
)


ContentUnion1 = TypeAliasType("ContentUnion1", Union[Content, List[Any]])


ContentUnion2TypedDict = TypeAliasType(
    "ContentUnion2TypedDict", Union[Dict[str, Any], ContentUnion1TypedDict]
)
r"""Returns the exact search query or list of sources."""


ContentUnion2 = TypeAliasType("ContentUnion2", Union[Dict[str, Any], ContentUnion1])
r"""Returns the exact search query or list of sources."""


class OutputTypedDict(TypedDict):
    type: NotRequired[str]
    r"""The type of the output."""
    text: NotRequired[str]
    r"""The text of the output."""
    content: NotRequired[ContentUnion2TypedDict]
    r"""Returns the exact search query or list of sources."""
    agent: NotRequired[str]
    r"""The agent used to generate the response."""


class Output(BaseModel):
    type: Optional[str] = None
    r"""The type of the output."""

    text: Optional[str] = None
    r"""The text of the output."""

    content: Optional[ContentUnion2] = None
    r"""Returns the exact search query or list of sources."""

    agent: Optional[str] = None
    r"""The agent used to generate the response."""


class PostV1AgentsRunsResponseBodyTypedDict(TypedDict):
    r"""Inference response in application/json or text/event-stream format."""

    output: NotRequired[List[OutputTypedDict]]


class PostV1AgentsRunsResponseBody(BaseModel):
    r"""Inference response in application/json or text/event-stream format."""

    output: Optional[List[Output]] = None


PostV1AgentsRunsResponseTypedDict = TypeAliasType(
    "PostV1AgentsRunsResponseTypedDict",
    Union[
        PostV1AgentsRunsResponseBodyTypedDict,
        Union[
            eventstreaming.EventStream[DataTypedDict],
            eventstreaming.EventStreamAsync[DataTypedDict],
        ],
    ],
)


PostV1AgentsRunsResponse = TypeAliasType(
    "PostV1AgentsRunsResponse",
    Union[
        PostV1AgentsRunsResponseBody,
        Union[eventstreaming.EventStream[Data], eventstreaming.EventStreamAsync[Data]],
    ],
)
