"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict
from youdotcom.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL


POST_V1_CONTENTS_OP_SERVERS = [
    "https://ydc-index.io",
]


FormatEnum2 = Literal[
    "html",
    "markdown",
]


FormatEnum1 = Literal[
    "html",
    "markdown",
]
r"""The format of the content to be returned."""


FormatTypedDict = TypeAliasType("FormatTypedDict", Union[FormatEnum1, FormatEnum2])
r"""The format of the content to be returned."""


Format = TypeAliasType("Format", Union[FormatEnum1, FormatEnum2])
r"""The format of the content to be returned."""


class PostV1ContentsRequestTypedDict(TypedDict):
    urls: NotRequired[List[str]]
    r"""Array of URLs to fetch the contents from."""
    format_: NotRequired[FormatTypedDict]
    r"""The format of the content to be returned."""


class PostV1ContentsRequest(BaseModel):
    urls: Optional[List[str]] = None
    r"""Array of URLs to fetch the contents from."""

    format_: Annotated[Optional[Format], pydantic.Field(alias="format")] = None
    r"""The format of the content to be returned."""


class PostV1ContentsResponseTypedDict(TypedDict):
    url: NotRequired[str]
    r"""The webpage URL whose content has been fetched."""
    title: NotRequired[str]
    r"""The title of the web page."""
    html: NotRequired[Nullable[str]]
    r"""The retrieved HTML content of the web page."""
    markdown: NotRequired[Nullable[str]]
    r"""The retrieved Markdown content of the web page."""


class PostV1ContentsResponse(BaseModel):
    url: Optional[str] = None
    r"""The webpage URL whose content has been fetched."""

    title: Optional[str] = None
    r"""The title of the web page."""

    html: OptionalNullable[str] = UNSET
    r"""The retrieved HTML content of the web page."""

    markdown: OptionalNullable[str] = UNSET
    r"""The retrieved Markdown content of the web page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["url", "title", "html", "markdown"]
        nullable_fields = ["html", "markdown"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
