"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .researcheffort import ResearchEffort
from .researchresponse import ResearchResponse, ResearchResponseTypedDict
from .taskresponse import TaskResponse, TaskResponseTypedDict
from pydantic import model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class SourceControlTypedDict(TypedDict):
    r"""Beta. Controls which web sources the research agent searches and visits. Use this to allow specific domains, block specific domains, boost specific domains, filter by recency, or focus web results by country.

    `include_domains` and `exclude_domains` cannot be used together. Each domain list is capped at 500 entries. `exclude_domains` also blocks the research agent from visiting pages on those domains during browsing. `boost_domains` gives matching domains a relative ranking boost without filtering out other domains. It can be combined with `exclude_domains` but cannot be combined with `include_domains`.
    """

    include_domains: NotRequired[List[str]]
    r"""Only return results from these domains. Max 500 domains. Cannot be used with exclude_domains or boost_domains."""
    exclude_domains: NotRequired[List[str]]
    r"""Never return results from these domains. Max 500 domains. Also blocks the research agent from visiting pages on those domains during browsing."""
    boost_domains: NotRequired[List[str]]
    r"""Boost results from these domains without excluding other domains. Max 500 domains. Cannot be used with include_domains."""
    freshness: NotRequired[str]
    r"""Filter results by recency. Accepts `day`, `week`, `month`, `year`, or a custom date range in `YYYY-MM-DDtoYYYY-MM-DD` format."""
    country: NotRequired[str]
    r"""ISO 3166-1 alpha-2 country code, such as US, GB, or DE, to geographically focus web results."""


class SourceControl(BaseModel):
    r"""Beta. Controls which web sources the research agent searches and visits. Use this to allow specific domains, block specific domains, boost specific domains, filter by recency, or focus web results by country.

    `include_domains` and `exclude_domains` cannot be used together. Each domain list is capped at 500 entries. `exclude_domains` also blocks the research agent from visiting pages on those domains during browsing. `boost_domains` gives matching domains a relative ranking boost without filtering out other domains. It can be combined with `exclude_domains` but cannot be combined with `include_domains`.
    """

    include_domains: Optional[List[str]] = None
    r"""Only return results from these domains. Max 500 domains. Cannot be used with exclude_domains or boost_domains."""

    exclude_domains: Optional[List[str]] = None
    r"""Never return results from these domains. Max 500 domains. Also blocks the research agent from visiting pages on those domains during browsing."""

    boost_domains: Optional[List[str]] = None
    r"""Boost results from these domains without excluding other domains. Max 500 domains. Cannot be used with include_domains."""

    freshness: Optional[str] = None
    r"""Filter results by recency. Accepts `day`, `week`, `month`, `year`, or a custom date range in `YYYY-MM-DDtoYYYY-MM-DD` format."""

    country: Optional[str] = None
    r"""ISO 3166-1 alpha-2 country code, such as US, GB, or DE, to geographically focus web results."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "include_domains",
                "exclude_domains",
                "boost_domains",
                "freshness",
                "country",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResearchRequestTypedDict(TypedDict):
    input: str
    r"""The research question or complex query requiring in-depth investigation and multi-step reasoning.

    Note: The maximum length of the input is 40,000 characters.
    """
    research_effort: NotRequired[ResearchEffort]
    r"""Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.

    Available levels:
    - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
    - `standard`: The default. Balances speed and depth, a good fit for most questions.
    - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
    - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
    - `frontier`: The highest-quality tier. Runs over longer durations with improved quality and accuracy. Only works with the task-based API (`background=true`); sending `frontier` without `background=true` returns a 422.
    """
    background: NotRequired[bool]
    r"""When true, queue a research task and return a task handle immediately instead of waiting for the result inline. Defaults to synchronous. When enabled, the response is a TaskResponse object with a task_id and stream_url for polling progress via GET /v1/research/{task_id} or streaming via GET /v1/research/{task_id}/stream."""
    source_control: NotRequired[SourceControlTypedDict]
    r"""Beta. Controls which web sources the research agent searches and visits. Use this to allow specific domains, block specific domains, boost specific domains, filter by recency, or focus web results by country.

    `include_domains` and `exclude_domains` cannot be used together. Each domain list is capped at 500 entries. `exclude_domains` also blocks the research agent from visiting pages on those domains during browsing. `boost_domains` gives matching domains a relative ranking boost without filtering out other domains. It can be combined with `exclude_domains` but cannot be combined with `include_domains`.
    """
    output_schema: NotRequired[Dict[str, Any]]
    r"""Beta. Requests structured JSON output in output.content using a supported JSON Schema subset. Supported only with research_effort values standard, deep, and exhaustive. Sending output_schema with research_effort: \"lite\" returns 422.

    Schema rules: Root must be a JSON object. Top-level anyOf is not allowed. Every object must define properties and set additionalProperties: false. Every property must be listed in required. Recursive schemas are not supported.

    Limits: Max nesting depth 5, max total properties 100, max total enum values 500, max total schema string budget 25,000.
    """


class ResearchRequest(BaseModel):
    input: str
    r"""The research question or complex query requiring in-depth investigation and multi-step reasoning.

    Note: The maximum length of the input is 40,000 characters.
    """

    research_effort: Optional[ResearchEffort] = ResearchEffort.STANDARD
    r"""Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.

    Available levels:
    - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
    - `standard`: The default. Balances speed and depth, a good fit for most questions.
    - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
    - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
    - `frontier`: The highest-quality tier. Runs over longer durations with improved quality and accuracy. Only works with the task-based API (`background=true`); sending `frontier` without `background=true` returns a 422.
    """

    background: Optional[bool] = False
    r"""When true, queue a research task and return a task handle immediately instead of waiting for the result inline. Defaults to synchronous. When enabled, the response is a TaskResponse object with a task_id and stream_url for polling progress via GET /v1/research/{task_id} or streaming via GET /v1/research/{task_id}/stream."""

    source_control: Optional[SourceControl] = None
    r"""Beta. Controls which web sources the research agent searches and visits. Use this to allow specific domains, block specific domains, boost specific domains, filter by recency, or focus web results by country.

    `include_domains` and `exclude_domains` cannot be used together. Each domain list is capped at 500 entries. `exclude_domains` also blocks the research agent from visiting pages on those domains during browsing. `boost_domains` gives matching domains a relative ranking boost without filtering out other domains. It can be combined with `exclude_domains` but cannot be combined with `include_domains`.
    """

    output_schema: Optional[Dict[str, Any]] = None
    r"""Beta. Requests structured JSON output in output.content using a supported JSON Schema subset. Supported only with research_effort values standard, deep, and exhaustive. Sending output_schema with research_effort: \"lite\" returns 422.

    Schema rules: Root must be a JSON object. Top-level anyOf is not allowed. Every object must define properties and set additionalProperties: false. Every property must be listed in required. Recursive schemas are not supported.

    Limits: Max nesting depth 5, max total properties 100, max total enum values 500, max total schema string budget 25,000.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["research_effort", "background", "source_control", "output_schema"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ResearchLocTypedDict = TypeAliasType("ResearchLocTypedDict", Union[str, int])


ResearchLoc = TypeAliasType("ResearchLoc", Union[str, int])


class ResearchInputTypedDict(TypedDict):
    pass


class ResearchInput(BaseModel):
    pass


ResearchInputUnionTypedDict = TypeAliasType(
    "ResearchInputUnionTypedDict", Union[ResearchInputTypedDict, str]
)
r"""The input value that caused the error."""


ResearchInputUnion = TypeAliasType("ResearchInputUnion", Union[ResearchInput, str])
r"""The input value that caused the error."""


class ResearchDetailTypedDict(TypedDict):
    type: str
    r"""The validation error type."""
    loc: List[ResearchLocTypedDict]
    r"""The location of the error as a path of segments (strings for field names, integers for byte offsets)."""
    msg: str
    r"""A human-readable description of the error."""
    input: ResearchInputUnionTypedDict
    r"""The input value that caused the error."""
    ctx: NotRequired[Dict[str, Any]]
    r"""Additional context about the error."""


class ResearchDetail(BaseModel):
    type: str
    r"""The validation error type."""

    loc: List[ResearchLoc]
    r"""The location of the error as a path of segments (strings for field names, integers for byte offsets)."""

    msg: str
    r"""A human-readable description of the error."""

    input: ResearchInputUnion
    r"""The input value that caused the error."""

    ctx: Optional[Dict[str, Any]] = None
    r"""Additional context about the error."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ctx"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


ResearchResultTypedDict = TypeAliasType(
    "ResearchResultTypedDict",
    Union[ResearchResponseTypedDict, TaskResponseTypedDict],
)
r"""A JSON object containing a comprehensive answer with citations and supporting search results. When background=true, returns a task handle instead."""


ResearchResult = TypeAliasType(
    "ResearchResult", Union[ResearchResponse, TaskResponse]
)
r"""A JSON object containing a comprehensive answer with citations and supporting search results. When background=true, returns a task handle instead."""
