"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pydantic import model_serializer
from typing import Any, Dict, List, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


ContentTypedDict = TypeAliasType("ContentTypedDict", Union[str, Dict[str, Any]])
r"""The comprehensive response with inline citations. When content_type is \"text\", this is a Markdown string with numbered citations that reference the items in the sources array. When content_type is \"object\", this is a structured JSON object matching the requested output_schema."""


Content = TypeAliasType("Content", Union[str, Dict[str, Any]])
r"""The comprehensive response with inline citations. When content_type is \"text\", this is a Markdown string with numbered citations that reference the items in the sources array. When content_type is \"object\", this is a structured JSON object matching the requested output_schema."""


class ContentType(str, Enum):
    r"""The format of the content field."""

    TEXT = "text"
    OBJECT = "object"


class SourceTypedDict(TypedDict):
    url: str
    r"""The URL of the source webpage."""
    title: NotRequired[str]
    r"""The title of the source webpage."""
    snippets: NotRequired[List[str]]
    r"""Relevant excerpts from the source page that were used in generating the answer."""


class Source(BaseModel):
    url: str
    r"""The URL of the source webpage."""

    title: Optional[str] = None
    r"""The title of the source webpage."""

    snippets: Optional[List[str]] = None
    r"""Relevant excerpts from the source page that were used in generating the answer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "snippets"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OutputTypedDict(TypedDict):
    r"""The research output containing the answer and sources."""

    content: ContentTypedDict
    r"""The comprehensive response with inline citations. When content_type is \"text\", this is a Markdown string with numbered citations that reference the items in the sources array. When content_type is \"object\", this is a structured JSON object matching the requested output_schema."""
    content_type: ContentType
    r"""The format of the content field."""
    sources: List[SourceTypedDict]
    r"""A list of web sources used to generate the answer."""


class Output(BaseModel):
    r"""The research output containing the answer and sources."""

    content: Content
    r"""The comprehensive response with inline citations. When content_type is \"text\", this is a Markdown string with numbered citations that reference the items in the sources array. When content_type is \"object\", this is a structured JSON object matching the requested output_schema."""

    content_type: ContentType
    r"""The format of the content field."""

    sources: List[Source]
    r"""A list of web sources used to generate the answer."""


class ResearchResponseTypedDict(TypedDict):
    output: OutputTypedDict
    r"""The research output containing the answer and sources."""


class ResearchResponse(BaseModel):
    output: Output
    r"""The research output containing the answer and sources."""
