"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ResearchResultsFullSourceTypedDict(TypedDict):
    url: NotRequired[str]
    title: NotRequired[str]
    snippet: NotRequired[str]


class ResearchResultsFullSource(BaseModel):
    url: Optional[str] = None

    title: Optional[str] = None

    snippet: Optional[str] = None


class ResearchResultsFullTypedDict(TypedDict):
    type: Literal["research.results"]
    report: NotRequired[str]
    sources: NotRequired[List[ResearchResultsFullSourceTypedDict]]


class ResearchResultsFull(BaseModel):
    TYPE: Annotated[
        Annotated[
            Literal["research.results"],
            AfterValidator(validate_const("research.results")),
        ],
        pydantic.Field(alias="type"),
    ] = "research.results"

    report: Optional[str] = None

    sources: Optional[List[ResearchResultsFullSource]] = None
