"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v1researchpostrequestbodycontentapplicationjsonschemaresearcheffort import (
    V1ResearchPostRequestBodyContentApplicationJSONSchemaResearchEffort,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL
from youdotcom.utils import FieldMetadata, HeaderMetadata, RequestMetadata


RESEARCH_OP_SERVERS = [
    "https://api.you.com",
]


class ResearchRequestBodyTypedDict(TypedDict):
    input: str
    r"""The research question or complex query requiring in-depth investigation and multi-step reasoning.

    Note: The maximum length of the input is 40,000 characters.
    """
    research_effort: NotRequired[
        V1ResearchPostRequestBodyContentApplicationJSONSchemaResearchEffort
    ]
    r"""Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.

    Available levels:
    - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
    - `standard`: The default. Balances speed and depth, a good fit for most questions.
    - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
    - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
    """


class ResearchRequestBody(BaseModel):
    input: str
    r"""The research question or complex query requiring in-depth investigation and multi-step reasoning.

    Note: The maximum length of the input is 40,000 characters.
    """

    research_effort: Optional[
        V1ResearchPostRequestBodyContentApplicationJSONSchemaResearchEffort
    ] = V1ResearchPostRequestBodyContentApplicationJSONSchemaResearchEffort.STANDARD
    r"""Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.

    Available levels:
    - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
    - `standard`: The default. Balances speed and depth, a good fit for most questions.
    - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
    - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["research_effort"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ResearchRequestTypedDict(TypedDict):
    x_api_key: str
    r"""A unique API Key is required to authorize API access. [Get your API Key with free credits](https://you.com/platform)."""
    body: NotRequired[ResearchRequestBodyTypedDict]


class ResearchRequest(BaseModel):
    x_api_key: Annotated[
        str,
        pydantic.Field(alias="X-API-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""A unique API Key is required to authorize API access. [Get your API Key with free credits](https://you.com/platform)."""

    body: Annotated[
        Optional[ResearchRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
