"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

# Manual overlay: `frontier` tier added via overlays/python_overlay.yaml
# until the upstream OpenAPI spec includes it. See that file for details.

from __future__ import annotations
from enum import Enum


class ResearchEffort(str, Enum):
    r"""Controls how much time and effort the Research API spends on your question. Higher effort levels run more searches and dig deeper into sources, at the cost of a longer response time.

    Available levels:
    - `lite`: Returns answers quickly. Good for straightforward questions that just need a fast, reliable answer.
    - `standard`: The default. Balances speed and depth, a good fit for most questions.
    - `deep`: Spends more time researching and cross-referencing sources. Use this when accuracy and thoroughness matter more than speed.
    - `exhaustive`: The most thorough option. Explores the topic as fully as possible, best suited for complex research tasks where you want the highest quality result.
    - `frontier`: The highest-quality tier. Runs over longer durations with improved quality and accuracy. Only works with the task-based API (``background=true``); sending ``frontier`` without ``background=true`` returns a 422.
    """

    LITE = "lite"
    STANDARD = "standard"
    DEEP = "deep"
    EXHAUSTIVE = "exhaustive"
    FRONTIER = "frontier"
