"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searcheffort_enum import SearchEffortEnum
from .verbosity import Verbosity
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


SearchEffortTypedDict = TypeAliasType(
    "SearchEffortTypedDict", Union[SearchEffortEnum, str]
)
r"""Search effort level for research: 'auto' lets agent decide"""


SearchEffort = TypeAliasType("SearchEffort", Union[SearchEffortEnum, str])
r"""Search effort level for research: 'auto' lets agent decide"""


ReportVerbosityTypedDict = TypeAliasType(
    "ReportVerbosityTypedDict", Union[Verbosity, str]
)


ReportVerbosity = TypeAliasType("ReportVerbosity", Union[Verbosity, str])


class ResearchToolTypedDict(TypedDict):
    r"""Research tool with configurable search effort and report verbosity"""

    type: Literal["research"]
    search_effort: NotRequired[SearchEffortTypedDict]
    r"""Search effort level for research: 'auto' lets agent decide"""
    report_verbosity: NotRequired[ReportVerbosityTypedDict]


class ResearchTool(BaseModel):
    r"""Research tool with configurable search effort and report verbosity"""

    TYPE: Annotated[
        Annotated[Literal["research"], AfterValidator(validate_const("research"))],
        pydantic.Field(alias="type"),
    ] = "research"

    search_effort: Optional[SearchEffort] = None
    r"""Search effort level for research: 'auto' lets agent decide"""

    report_verbosity: Optional[ReportVerbosity] = None
