"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ResponseOutputTextDeltaResponseTypedDict(TypedDict):
    output_index: int
    delta: str
    r"""Incremental text content"""
    type: Literal["message.answer"]


class ResponseOutputTextDeltaResponse(BaseModel):
    output_index: int

    delta: str
    r"""Incremental text content"""

    TYPE: Annotated[
        Annotated[
            Literal["message.answer"], AfterValidator(validate_const("message.answer"))
        ],
        pydantic.Field(alias="type"),
    ] = "message.answer"


class ResponseOutputTextDeltaTypedDict(TypedDict):
    seq_id: int
    response: ResponseOutputTextDeltaResponseTypedDict
    type: Literal["response.output_text.delta"]


class ResponseOutputTextDelta(BaseModel):
    seq_id: int

    response: ResponseOutputTextDeltaResponse

    TYPE: Annotated[
        Annotated[
            Literal["response.output_text.delta"],
            AfterValidator(validate_const("response.output_text.delta")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.output_text.delta"
