"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ResponseCreatedTypedDict(TypedDict):
    r"""SSE event signifying the response stream has been created"""

    seq_id: int
    type: Literal["response.created"]


class ResponseCreated(BaseModel):
    r"""SSE event signifying the response stream has been created"""

    seq_id: int

    TYPE: Annotated[
        Annotated[
            Literal["response.created"],
            AfterValidator(validate_const("response.created")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.created"
