"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentrunsresponsewebsearchresult import (
    AgentRunsResponseWebSearchResult,
    AgentRunsResponseWebSearchResultTypedDict,
)
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ResponseOutputContentFullResponseTypedDict(TypedDict):
    output_index: int
    full: List[AgentRunsResponseWebSearchResultTypedDict]
    r"""Complete web search results"""
    type: Literal["web_search.results"]


class ResponseOutputContentFullResponse(BaseModel):
    output_index: int

    full: List[AgentRunsResponseWebSearchResult]
    r"""Complete web search results"""

    TYPE: Annotated[
        Annotated[
            Literal["web_search.results"],
            AfterValidator(validate_const("web_search.results")),
        ],
        pydantic.Field(alias="type"),
    ] = "web_search.results"


class ResponseOutputContentFullTypedDict(TypedDict):
    seq_id: int
    response: ResponseOutputContentFullResponseTypedDict
    type: Literal["response.output_content.full"]


class ResponseOutputContentFull(BaseModel):
    seq_id: int

    response: ResponseOutputContentFullResponse

    TYPE: Annotated[
        Annotated[
            Literal["response.output_content.full"],
            AfterValidator(validate_const("response.output_content.full")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.output_content.full"
