"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ResponseOutputItemDoneResponseTypedDict(TypedDict):
    output_index: int


class ResponseOutputItemDoneResponse(BaseModel):
    output_index: int


class ResponseOutputItemDoneTypedDict(TypedDict):
    seq_id: int
    response: ResponseOutputItemDoneResponseTypedDict
    type: Literal["response.output_item.done"]


class ResponseOutputItemDone(BaseModel):
    seq_id: int

    response: ResponseOutputItemDoneResponse

    TYPE: Annotated[
        Annotated[
            Literal["response.output_item.done"],
            AfterValidator(validate_const("response.output_item.done")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.output_item.done"
