"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class ResponseStartingTypedDict(TypedDict):
    r"""SSE event signifying the response is starting"""

    seq_id: int
    type: Literal["response.starting"]


class ResponseStarting(BaseModel):
    r"""SSE event signifying the response is starting"""

    seq_id: int

    TYPE: Annotated[
        Annotated[
            Literal["response.starting"],
            AfterValidator(validate_const("response.starting")),
        ],
        pydantic.Field(alias="type"),
    ] = "response.starting"
