"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


SafeSearch = Literal[
    "off",
    "moderate",
    "strict",
]
r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""
