"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class SearchMetadataTypedDict(TypedDict):
    search_uuid: NotRequired[str]
    query: NotRequired[str]
    r"""Returns the search query used to retrieve the results."""
    latency: NotRequired[float]


class SearchMetadata(BaseModel):
    search_uuid: Optional[str] = None

    query: Optional[str] = None
    r"""Returns the search query used to retrieve the results."""

    latency: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["search_uuid", "query", "latency"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
