"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SearchEffort(str, Enum):
    r"""This parameter maps to different configurations regarding the depth of research the tool can perform. Its values range from `low`, `medium` to `high`.

    Alternatively, use `auto` mode for a more dynamic search approach, allowing the tool the freedom to adjust its subparameters.
    """

    AUTO = "auto"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
