"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .country import Country
from .freshnessvalue import FreshnessValue, FreshnessValueTypedDict
from .language import Language
from .livecrawl import LiveCrawl
from .livecrawlformats import LiveCrawlFormats
from .safesearch import SafeSearch
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class SearchRequestBodyTypedDict(TypedDict):
    query: str
    r"""The search query used to retrieve relevant results from the web. You can also include [search operators](https://docs.you.com/search/search-operators) to refine your search."""
    count: NotRequired[int]
    r"""Specifies the maximum number of search results to return per section (the sections are `web` and `news`. See the JSON response to visualize them)."""
    freshness: NotRequired[FreshnessValueTypedDict]
    r"""Specifies the freshness of the results to return. Provide either one of `day`, `week`, `month`, `year`, or a date range string in the format `YYYY-MM-DDtoYYYY-MM-DD`.

    When your search query includes a temporal keyword and you also set a freshness parameter, the search will use the broader (i.e., less restrictive) of the two timeframes. For example, if you use `query=news+this+week&freshness=month`, the results will use a freshness of month.
    """
    offset: NotRequired[int]
    r"""Indicates the `offset` for pagination. The `offset` is calculated in multiples of `count`. For example, if `count = 5` and `offset = 1`, results 5–10 will be returned. Range `0 ≤ offset ≤ 9`."""
    country: NotRequired[Country]
    r"""The country code that determines the geographical focus of the web results."""
    language: NotRequired[Language]
    r"""The language of the web results that will be returned (BCP 47 format)."""
    safesearch: NotRequired[SafeSearch]
    r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""
    livecrawl: NotRequired[LiveCrawl]
    r"""Indicates which section(s) of search results to livecrawl and return full page content."""
    livecrawl_formats: NotRequired[List[LiveCrawlFormats]]
    r"""Indicates the format(s) of the livecrawled content. Pass one or both values (`html`, `markdown`). In a GET request, repeat the parameter: `?livecrawl_formats=html&livecrawl_formats=markdown`. In a POST body, provide a JSON array: `[\"html\", \"markdown\"]`."""
    include_domains: NotRequired[List[str]]
    r"""A list of domains to restrict search results to. Only results from these domains will be returned. Supports up to 500 domains. This is a strict allowlist, not a boost — results are limited exclusively to the specified domains.

    Cannot be combined with `exclude_domains`; passing both will return a `422` error.
    """
    exclude_domains: NotRequired[List[str]]
    r"""A list of domains to exclude from search results. Results from these domains will be filtered out. Supports up to 500 domains.

    Cannot be combined with `include_domains`; passing both will return a `422` error.
    """
    boost_domains: NotRequired[List[str]]
    r"""A list of domains to boost in search ranking. Matching results from these domains receive a relative ranking boost, but results are not limited to these domains. Supports up to 500 domains. Can be combined with `exclude_domains`, but cannot be combined with `include_domains` (returns `422`)."""
    crawl_timeout: NotRequired[int]
    r"""Maximum time in seconds to wait for page content when `livecrawl` is enabled. Must be between 1 and 60 seconds. Default is 10 seconds."""


class SearchRequestBody(BaseModel):
    query: str
    r"""The search query used to retrieve relevant results from the web. You can also include [search operators](https://docs.you.com/search/search-operators) to refine your search."""

    count: Optional[int] = 10
    r"""Specifies the maximum number of search results to return per section (the sections are `web` and `news`. See the JSON response to visualize them)."""

    freshness: Optional[FreshnessValue] = None
    r"""Specifies the freshness of the results to return. Provide either one of `day`, `week`, `month`, `year`, or a date range string in the format `YYYY-MM-DDtoYYYY-MM-DD`.

    When your search query includes a temporal keyword and you also set a freshness parameter, the search will use the broader (i.e., less restrictive) of the two timeframes. For example, if you use `query=news+this+week&freshness=month`, the results will use a freshness of month.
    """

    offset: Optional[int] = None
    r"""Indicates the `offset` for pagination. The `offset` is calculated in multiples of `count`. For example, if `count = 5` and `offset = 1`, results 5–10 will be returned. Range `0 ≤ offset ≤ 9`."""

    country: Optional[Country] = None
    r"""The country code that determines the geographical focus of the web results."""

    language: Optional[Language] = Language.EN
    r"""The language of the web results that will be returned (BCP 47 format)."""

    safesearch: Optional[SafeSearch] = None
    r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""

    livecrawl: Optional[LiveCrawl] = None
    r"""Indicates which section(s) of search results to livecrawl and return full page content."""

    livecrawl_formats: Optional[List[LiveCrawlFormats]] = None
    r"""Indicates the format(s) of the livecrawled content. Pass one or both values (`html`, `markdown`). In a GET request, repeat the parameter: `?livecrawl_formats=html&livecrawl_formats=markdown`. In a POST body, provide a JSON array: `[\"html\", \"markdown\"]`."""

    include_domains: Optional[List[str]] = None
    r"""A list of domains to restrict search results to. Only results from these domains will be returned. Supports up to 500 domains. This is a strict allowlist, not a boost — results are limited exclusively to the specified domains.

    Cannot be combined with `exclude_domains`; passing both will return a `422` error.
    """

    exclude_domains: Optional[List[str]] = None
    r"""A list of domains to exclude from search results. Results from these domains will be filtered out. Supports up to 500 domains.

    Cannot be combined with `include_domains`; passing both will return a `422` error.
    """

    boost_domains: Optional[List[str]] = None
    r"""A list of domains to boost in search ranking. Matching results from these domains receive a relative ranking boost, but results are not limited to these domains. Supports up to 500 domains. Can be combined with `exclude_domains`, but cannot be combined with `include_domains` (returns `422`)."""

    crawl_timeout: Optional[int] = 10
    r"""Maximum time in seconds to wait for page content when `livecrawl` is enabled. Must be between 1 and 60 seconds. Default is 10 seconds."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "count",
                "freshness",
                "offset",
                "country",
                "language",
                "safesearch",
                "livecrawl",
                "livecrawl_formats",
                "include_domains",
                "exclude_domains",
                "boost_domains",
                "crawl_timeout",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
