"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


SearchEffortEnum = Literal[
    "low",
    "medium",
    "high",
    "auto",
]
r"""Search effort level for research: 'auto' lets agent decide"""
