"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .country import Country
from .freshnessvalue import FreshnessValue, FreshnessValueTypedDict
from .language import Language
from .livecrawl import LiveCrawl
from .livecrawlformats import LiveCrawlFormats
from .safesearch import SafeSearch
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL
from youdotcom.utils import FieldMetadata, QueryParamMetadata


SEARCH_OP_SERVERS = [
    "https://ydc-index.io",
]


class SearchRequestTypedDict(TypedDict):
    query: str
    count: NotRequired[int]
    freshness: NotRequired[FreshnessValueTypedDict]
    r"""Specifies the freshness of the results to return. Provide either one of `day`, `week`, `month`, `year`, or a date range string in the format `YYYY-MM-DDtoYYYY-MM-DD`.

    When your search query includes a temporal keyword and you also set a freshness parameter, the search will use the broader (i.e., less restrictive) of the two timeframes. For example, if you use `query=news+this+week&freshness=month`, the results will use a freshness of month.
    """
    offset: NotRequired[int]
    country: NotRequired[Country]
    r"""The country code that determines the geographical focus of the web results."""
    language: NotRequired[Language]
    r"""The language of the web results that will be returned (BCP 47 format)."""
    safesearch: NotRequired[SafeSearch]
    r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""
    livecrawl: NotRequired[LiveCrawl]
    r"""Indicates which section(s) of search results to livecrawl and return full page content."""
    livecrawl_formats: NotRequired[List[LiveCrawlFormats]]
    include_domains: NotRequired[str]
    r"""A list of domains to restrict search results to. Only results from these domains will be returned. For large domain lists (up to 500), use POST with a JSON array instead. This is a strict allowlist — cannot be combined with `exclude_domains` (returns `422`).

    **Important:** Use a single comma-separated value (e.g. `include_domains=nytimes.com,bbc.com`). Repeated parameters (`include_domains=a.com&include_domains=b.com`) are not supported.
    """
    exclude_domains: NotRequired[str]
    r"""A list of domains to exclude from search results. Results from these domains will be filtered out. For large domain lists (up to 500), use POST with a JSON array instead. Cannot be combined with `include_domains` (returns `422`).

    **Important:** You must use a single comma-separated value (e.g. `exclude_domains=spam-site.com,other-site.com`). Repeated parameters are not supported.
    """
    boost_domains: NotRequired[str]
    r"""A list of domains to boost in search ranking. Matching results from these domains receive a relative ranking boost, but results are not limited to these domains. Supports up to 500 domains. Can be combined with `exclude_domains`, but cannot be combined with `include_domains` (returns `422`).

    **Important:** You must use a single comma-separated value (e.g. `boost_domains=nytimes.com,wired.com`). Repeated parameters are not supported.
    """
    crawl_timeout: NotRequired[int]


class SearchRequest(BaseModel):
    query: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]

    count: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10

    freshness: Annotated[
        Optional[FreshnessValue],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the freshness of the results to return. Provide either one of `day`, `week`, `month`, `year`, or a date range string in the format `YYYY-MM-DDtoYYYY-MM-DD`.

    When your search query includes a temporal keyword and you also set a freshness parameter, the search will use the broader (i.e., less restrictive) of the two timeframes. For example, if you use `query=news+this+week&freshness=month`, the results will use a freshness of month.
    """

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    country: Annotated[
        Optional[Country],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The country code that determines the geographical focus of the web results."""

    language: Annotated[
        Optional[Language],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = Language.EN
    r"""The language of the web results that will be returned (BCP 47 format)."""

    safesearch: Annotated[
        Optional[SafeSearch],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not."""

    livecrawl: Annotated[
        Optional[LiveCrawl],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Indicates which section(s) of search results to livecrawl and return full page content."""

    livecrawl_formats: Annotated[
        Optional[List[LiveCrawlFormats]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    include_domains: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A list of domains to restrict search results to. Only results from these domains will be returned. For large domain lists (up to 500), use POST with a JSON array instead. This is a strict allowlist — cannot be combined with `exclude_domains` (returns `422`).

    **Important:** Use a single comma-separated value (e.g. `include_domains=nytimes.com,bbc.com`). Repeated parameters (`include_domains=a.com&include_domains=b.com`) are not supported.
    """

    exclude_domains: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A list of domains to exclude from search results. Results from these domains will be filtered out. For large domain lists (up to 500), use POST with a JSON array instead. Cannot be combined with `include_domains` (returns `422`).

    **Important:** You must use a single comma-separated value (e.g. `exclude_domains=spam-site.com,other-site.com`). Repeated parameters are not supported.
    """

    boost_domains: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A list of domains to boost in search ranking. Matching results from these domains receive a relative ranking boost, but results are not limited to these domains. Supports up to 500 domains. Can be combined with `exclude_domains`, but cannot be combined with `include_domains` (returns `422`).

    **Important:** You must use a single comma-separated value (e.g. `boost_domains=nytimes.com,wired.com`). Repeated parameters are not supported.
    """

    crawl_timeout: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 10

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "count",
                "freshness",
                "offset",
                "country",
                "language",
                "safesearch",
                "livecrawl",
                "livecrawl_formats",
                "include_domains",
                "exclude_domains",
                "boost_domains",
                "crawl_timeout",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
