"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchrequestbody import SearchRequestBody, SearchRequestBodyTypedDict
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL
from youdotcom.utils import FieldMetadata, HeaderMetadata, RequestMetadata


SEARCH_POST_OP_SERVERS = [
    "https://ydc-index.io",
]


class SearchPostRequestTypedDict(TypedDict):
    x_api_key: str
    r"""A unique API Key is required to authorize API access. [Get your API Key with free credits](https://you.com/platform)."""
    body: NotRequired[SearchRequestBodyTypedDict]


class SearchPostRequest(BaseModel):
    x_api_key: Annotated[
        str,
        pydantic.Field(alias="X-API-Key"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""A unique API Key is required to authorize API access. [Get your API Key with free credits](https://you.com/platform)."""

    body: Annotated[
        Optional[SearchRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
