"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL
from youdotcom.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata


class StreamResearchTaskRequestTypedDict(TypedDict):
    task_id: str
    r"""The UUID of the research task."""
    from_id: NotRequired[int]
    r"""Resume from a sequence number for reconnection."""


class StreamResearchTaskRequest(BaseModel):
    task_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The UUID of the research task."""

    from_id: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Resume from a sequence number for reconnection."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["from_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
