"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from typing_extensions import TypedDict
from youdotcom.types import BaseModel


class TaskResponseStatus(str, Enum):
    r"""Current status of the task."""

    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class TaskResponseTypedDict(TypedDict):
    task_id: str
    r"""Unique identifier for the task."""
    type: str
    r"""Task type."""
    status: TaskResponseStatus
    r"""Current status of the task."""
    stream_url: str
    r"""URL to stream task events via SSE."""
    created_at: datetime
    r"""When the task was created."""


class TaskResponse(BaseModel):
    task_id: str
    r"""Unique identifier for the task."""

    type: str
    r"""Task type."""

    status: TaskResponseStatus
    r"""Current status of the task."""

    stream_url: str
    r"""URL to stream task events via SSE."""

    created_at: datetime
    r"""When the task was created."""
