"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


Trigger = Literal[
    "intent",
    "force",
]
r"""Tool trigger mode: 'intent' lets agent decide, 'force' always uses the tool"""
