"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Union
from typing_extensions import TypeAliasType


V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItemsTypedDict = TypeAliasType(
    "V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItemsTypedDict",
    Union[str, int],
)


V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItems = TypeAliasType(
    "V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItems",
    Union[str, int],
)
