"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .v1researchpostresponsescontentapplicationjsonschemadetailitemsinput import (
    V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInput,
    V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInputTypedDict,
)
from .v1researchpostresponsescontentapplicationjsonschemadetailitemslocitems import (
    V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItems,
    V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItemsTypedDict,
)
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsTypedDict(
    TypedDict
):
    type: str
    r"""The validation error type."""
    loc: List[
        V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItemsTypedDict
    ]
    r"""The location of the error as a path of segments (strings for field names, integers for byte offsets)."""
    msg: str
    r"""A human-readable description of the error."""
    input: V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInputTypedDict
    r"""The input value that caused the error."""
    ctx: NotRequired[Dict[str, Any]]
    r"""Additional context about the error."""


class V1ResearchPostResponsesContentApplicationJSONSchemaDetailItems(BaseModel):
    type: str
    r"""The validation error type."""

    loc: List[V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsLocItems]
    r"""The location of the error as a path of segments (strings for field names, integers for byte offsets)."""

    msg: str
    r"""A human-readable description of the error."""

    input: V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInput
    r"""The input value that caused the error."""

    ctx: Optional[Dict[str, Any]] = None
    r"""Additional context about the error."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ctx"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
