"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class V1ResearchPostResponsesContentApplicationJSONSchemaOutputContentType(str, Enum):
    r"""The format of the content field."""

    TEXT = "text"
