"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Any, Dict, Union
from typing_extensions import TypeAliasType


V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInputTypedDict = (
    TypeAliasType(
        "V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInputTypedDict",
        Union[str, Dict[str, Any]],
    )
)
r"""The input value that caused the error."""


V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInput = TypeAliasType(
    "V1ResearchPostResponsesContentApplicationJSONSchemaDetailItemsInput",
    Union[str, Dict[str, Any]],
)
r"""The input value that caused the error."""
