"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict
from youdotcom.types import BaseModel, UNSET_SENTINEL


class V1ResearchPostResponsesContentApplicationJSONSchemaOutputSourcesItemsTypedDict(
    TypedDict
):
    url: str
    r"""The URL of the source webpage."""
    title: NotRequired[str]
    r"""The title of the source webpage."""
    snippets: NotRequired[List[str]]
    r"""Relevant excerpts from the source page that were used in generating the answer."""


class V1ResearchPostResponsesContentApplicationJSONSchemaOutputSourcesItems(BaseModel):
    url: str
    r"""The URL of the source webpage."""

    title: Optional[str] = None
    r"""The title of the source webpage."""

    snippets: Optional[List[str]] = None
    r"""Relevant excerpts from the source page that were used in generating the answer."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["title", "snippets"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
