"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal
from typing_extensions import Annotated, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class WebSearchToolTypedDict(TypedDict):
    type: Literal["web_search"]
    r"""Setting this value to \"web_search\" is mandatory to use the web_search tool."""


class WebSearchTool(BaseModel):
    TYPE: Annotated[
        Annotated[Literal["web_search"], AfterValidator(validate_const("web_search"))],
        pydantic.Field(alias="type"),
    ] = "web_search"
    r"""Setting this value to \"web_search\" is mandatory to use the web_search tool."""
