"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .trigger import Trigger
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict
from youdotcom.types import BaseModel
from youdotcom.utils import validate_const


class WebSearchToolTypedDict(TypedDict):
    r"""Web search tool with optional intent-based triggering"""

    type: Literal["web_search"]
    trigger: NotRequired[Trigger]
    r"""Tool trigger mode: 'intent' lets agent decide, 'force' always uses the tool"""


class WebSearchTool(BaseModel):
    r"""Web search tool with optional intent-based triggering"""

    TYPE: Annotated[
        Annotated[Literal["web_search"], AfterValidator(validate_const("web_search"))],
        pydantic.Field(alias="type"),
    ] = "web_search"

    trigger: Optional[Trigger] = None
    r"""Tool trigger mode: 'intent' lets agent decide, 'force' always uses the tool"""
