"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .youerror import YouError
from typing import TYPE_CHECKING
from importlib import import_module
import builtins
import sys

if TYPE_CHECKING:
    from .agentruns400response_error import (
        AgentRuns400ResponseError,
        AgentRuns400ResponseErrorData,
    )
    from .agentruns401response_error import (
        AgentRuns401ResponseError,
        AgentRuns401ResponseErrorData,
    )
    from .agentruns422response_error import (
        AgentRuns422ResponseError,
        AgentRuns422ResponseErrorData,
    )
    from .contentsop import (
        ContentsForbiddenError,
        ContentsForbiddenErrorData,
        ContentsInternalServerError,
        ContentsInternalServerErrorData,
        ContentsUnauthorizedError,
        ContentsUnauthorizedErrorData,
    )
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError
    from .searchop import (
        SearchForbiddenError,
        SearchForbiddenErrorData,
        SearchInternalServerError,
        SearchInternalServerErrorData,
        SearchUnauthorizedError,
        SearchUnauthorizedErrorData,
    )
    from .youdefaulterror import YouDefaultError

__all__ = [
    "AgentRuns400ResponseError",
    "AgentRuns400ResponseErrorData",
    "AgentRuns401ResponseError",
    "AgentRuns401ResponseErrorData",
    "AgentRuns422ResponseError",
    "AgentRuns422ResponseErrorData",
    "ContentsForbiddenError",
    "ContentsForbiddenErrorData",
    "ContentsInternalServerError",
    "ContentsInternalServerErrorData",
    "ContentsUnauthorizedError",
    "ContentsUnauthorizedErrorData",
    "NoResponseError",
    "ResponseValidationError",
    "SearchForbiddenError",
    "SearchForbiddenErrorData",
    "SearchInternalServerError",
    "SearchInternalServerErrorData",
    "SearchUnauthorizedError",
    "SearchUnauthorizedErrorData",
    "YouDefaultError",
    "YouError",
]

_dynamic_imports: dict[str, str] = {
    "AgentRuns400ResponseError": ".agentruns400response_error",
    "AgentRuns400ResponseErrorData": ".agentruns400response_error",
    "AgentRuns401ResponseError": ".agentruns401response_error",
    "AgentRuns401ResponseErrorData": ".agentruns401response_error",
    "AgentRuns422ResponseError": ".agentruns422response_error",
    "AgentRuns422ResponseErrorData": ".agentruns422response_error",
    "ContentsForbiddenError": ".contentsop",
    "ContentsForbiddenErrorData": ".contentsop",
    "ContentsInternalServerError": ".contentsop",
    "ContentsInternalServerErrorData": ".contentsop",
    "ContentsUnauthorizedError": ".contentsop",
    "ContentsUnauthorizedErrorData": ".contentsop",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
    "SearchForbiddenError": ".searchop",
    "SearchForbiddenErrorData": ".searchop",
    "SearchInternalServerError": ".searchop",
    "SearchInternalServerErrorData": ".searchop",
    "SearchUnauthorizedError": ".searchop",
    "SearchUnauthorizedErrorData": ".searchop",
    "YouDefaultError": ".youdefaulterror",
}


def dynamic_import(modname, retries=3):
    for attempt in range(retries):
        try:
            return import_module(modname, __package__)
        except KeyError:
            # Clear any half-initialized module and retry
            sys.modules.pop(modname, None)
            if attempt == retries - 1:
                break
    raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")


def __getattr__(attr_name: str) -> object:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(
            f"No {attr_name} found in _dynamic_imports for module name -> {__name__} "
        )

    try:
        module = dynamic_import(module_name)
        result = getattr(module, attr_name)
        return result
    except ImportError as e:
        raise ImportError(
            f"Failed to import {attr_name} from {module_name}: {e}"
        ) from e
    except AttributeError as e:
        raise AttributeError(
            f"Failed to get {attr_name} from {module_name}: {e}"
        ) from e


def __dir__():
    lazy_attrs = builtins.list(_dynamic_imports.keys())
    return builtins.sorted(lazy_attrs)
