"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .youerror import YouError
from typing import Any, TYPE_CHECKING

from youdotcom.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .agentruns400response_error import (
        AgentRuns400ResponseError,
        AgentRuns400ResponseErrorData,
    )
    from .agentruns401response_error import (
        AgentRuns401ResponseError,
        AgentRuns401ResponseErrorData,
    )
    from .agentruns422response_error import (
        AgentRuns422ResponseError,
        AgentRuns422ResponseErrorData,
    )
    from .contentsrequestforbiddenerror import (
        ContentsRequestForbiddenError,
        ContentsRequestForbiddenErrorData,
    )
    from .contentsrequestinternalservererror import (
        ContentsRequestInternalServerError,
        ContentsRequestInternalServerErrorData,
    )
    from .contentsrequestunauthorizederror import (
        ContentsRequestUnauthorizedError,
        ContentsRequestUnauthorizedErrorData,
    )
    from .no_response_error import NoResponseError
    from .researchrequestforbiddenerror import (
        ResearchRequestForbiddenError,
        ResearchRequestForbiddenErrorData,
    )
    from .researchrequestinternalservererror import (
        ResearchRequestInternalServerError,
        ResearchRequestInternalServerErrorData,
    )
    from .researchrequestunauthorizederror import (
        ResearchRequestUnauthorizedError,
        ResearchRequestUnauthorizedErrorData,
    )
    from .researchrequestunprocessableentityerror import (
        ResearchRequestUnprocessableEntityError,
        ResearchRequestUnprocessableEntityErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .searchpostrequestforbiddenerror import (
        SearchPostRequestForbiddenError,
        SearchPostRequestForbiddenErrorData,
    )
    from .searchpostrequestinternalservererror import (
        SearchPostRequestInternalServerError,
        SearchPostRequestInternalServerErrorData,
    )
    from .searchpostrequestunauthorizederror import (
        SearchPostRequestUnauthorizedError,
        SearchPostRequestUnauthorizedErrorData,
    )
    from .searchpostrequestunprocessableentityerror import (
        SearchPostRequestUnprocessableEntityError,
        SearchPostRequestUnprocessableEntityErrorData,
    )
    from .searchrequestforbiddenerror import (
        SearchRequestForbiddenError,
        SearchRequestForbiddenErrorData,
    )
    from .searchrequestinternalservererror import (
        SearchRequestInternalServerError,
        SearchRequestInternalServerErrorData,
    )
    from .searchrequestunauthorizederror import (
        SearchRequestUnauthorizedError,
        SearchRequestUnauthorizedErrorData,
    )
    from .searchrequestunprocessableentityerror import (
        SearchRequestUnprocessableEntityError,
        SearchRequestUnprocessableEntityErrorData,
    )
    from .youdefaulterror import YouDefaultError

__all__ = [
    "AgentRuns400ResponseError",
    "AgentRuns400ResponseErrorData",
    "AgentRuns401ResponseError",
    "AgentRuns401ResponseErrorData",
    "AgentRuns422ResponseError",
    "AgentRuns422ResponseErrorData",
    "ContentsRequestForbiddenError",
    "ContentsRequestForbiddenErrorData",
    "ContentsRequestInternalServerError",
    "ContentsRequestInternalServerErrorData",
    "ContentsRequestUnauthorizedError",
    "ContentsRequestUnauthorizedErrorData",
    "NoResponseError",
    "ResearchRequestForbiddenError",
    "ResearchRequestForbiddenErrorData",
    "ResearchRequestInternalServerError",
    "ResearchRequestInternalServerErrorData",
    "ResearchRequestUnauthorizedError",
    "ResearchRequestUnauthorizedErrorData",
    "ResearchRequestUnprocessableEntityError",
    "ResearchRequestUnprocessableEntityErrorData",
    "ResponseValidationError",
    "SearchPostRequestForbiddenError",
    "SearchPostRequestForbiddenErrorData",
    "SearchPostRequestInternalServerError",
    "SearchPostRequestInternalServerErrorData",
    "SearchPostRequestUnauthorizedError",
    "SearchPostRequestUnauthorizedErrorData",
    "SearchPostRequestUnprocessableEntityError",
    "SearchPostRequestUnprocessableEntityErrorData",
    "SearchRequestForbiddenError",
    "SearchRequestForbiddenErrorData",
    "SearchRequestInternalServerError",
    "SearchRequestInternalServerErrorData",
    "SearchRequestUnauthorizedError",
    "SearchRequestUnauthorizedErrorData",
    "SearchRequestUnprocessableEntityError",
    "SearchRequestUnprocessableEntityErrorData",
    "YouDefaultError",
    "YouError",
]

_dynamic_imports: dict[str, str] = {
    "AgentRuns400ResponseError": ".agentruns400response_error",
    "AgentRuns400ResponseErrorData": ".agentruns400response_error",
    "AgentRuns401ResponseError": ".agentruns401response_error",
    "AgentRuns401ResponseErrorData": ".agentruns401response_error",
    "AgentRuns422ResponseError": ".agentruns422response_error",
    "AgentRuns422ResponseErrorData": ".agentruns422response_error",
    "ContentsRequestForbiddenError": ".contentsrequestforbiddenerror",
    "ContentsRequestForbiddenErrorData": ".contentsrequestforbiddenerror",
    "ContentsRequestInternalServerError": ".contentsrequestinternalservererror",
    "ContentsRequestInternalServerErrorData": ".contentsrequestinternalservererror",
    "ContentsRequestUnauthorizedError": ".contentsrequestunauthorizederror",
    "ContentsRequestUnauthorizedErrorData": ".contentsrequestunauthorizederror",
    "NoResponseError": ".no_response_error",
    "ResearchRequestForbiddenError": ".researchrequestforbiddenerror",
    "ResearchRequestForbiddenErrorData": ".researchrequestforbiddenerror",
    "ResearchRequestInternalServerError": ".researchrequestinternalservererror",
    "ResearchRequestInternalServerErrorData": ".researchrequestinternalservererror",
    "ResearchRequestUnauthorizedError": ".researchrequestunauthorizederror",
    "ResearchRequestUnauthorizedErrorData": ".researchrequestunauthorizederror",
    "ResearchRequestUnprocessableEntityError": ".researchrequestunprocessableentityerror",
    "ResearchRequestUnprocessableEntityErrorData": ".researchrequestunprocessableentityerror",
    "ResponseValidationError": ".responsevalidationerror",
    "SearchPostRequestForbiddenError": ".searchpostrequestforbiddenerror",
    "SearchPostRequestForbiddenErrorData": ".searchpostrequestforbiddenerror",
    "SearchPostRequestInternalServerError": ".searchpostrequestinternalservererror",
    "SearchPostRequestInternalServerErrorData": ".searchpostrequestinternalservererror",
    "SearchPostRequestUnauthorizedError": ".searchpostrequestunauthorizederror",
    "SearchPostRequestUnauthorizedErrorData": ".searchpostrequestunauthorizederror",
    "SearchPostRequestUnprocessableEntityError": ".searchpostrequestunprocessableentityerror",
    "SearchPostRequestUnprocessableEntityErrorData": ".searchpostrequestunprocessableentityerror",
    "SearchRequestForbiddenError": ".searchrequestforbiddenerror",
    "SearchRequestForbiddenErrorData": ".searchrequestforbiddenerror",
    "SearchRequestInternalServerError": ".searchrequestinternalservererror",
    "SearchRequestInternalServerErrorData": ".searchrequestinternalservererror",
    "SearchRequestUnauthorizedError": ".searchrequestunauthorizederror",
    "SearchRequestUnauthorizedErrorData": ".searchrequestunauthorizederror",
    "SearchRequestUnprocessableEntityError": ".searchrequestunprocessableentityerror",
    "SearchRequestUnprocessableEntityErrorData": ".searchrequestunprocessableentityerror",
    "YouDefaultError": ".youdefaulterror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
