"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import Optional
from youdotcom.errors import YouError
from youdotcom.types import BaseModel


class AgentRuns401ResponseErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class AgentRuns401ResponseError(YouError):
    r"""The message returned by the error"""

    data: AgentRuns401ResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: AgentRuns401ResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
