"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import Optional
from youdotcom.errors import YouError
from youdotcom.types import BaseModel


class ContentsInternalServerErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class ContentsInternalServerError(YouError):
    r"""Internal Server Error"""

    data: ContentsInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: ContentsInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ContentsForbiddenErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class ContentsForbiddenError(YouError):
    r"""Forbidden"""

    data: ContentsForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: ContentsForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ContentsUnauthorizedErrorData(BaseModel):
    detail: Optional[str] = None
    r"""Error detail message."""


@dataclass(unsafe_hash=True)
class ContentsUnauthorizedError(YouError):
    r"""Unauthorized"""

    data: ContentsUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: ContentsUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
