"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import List, Optional
from youdotcom.errors import YouError
from youdotcom.models import finance_researchop as models_finance_researchop
from youdotcom.types import BaseModel


class FinanceResearchInternalServerErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class FinanceResearchInternalServerError(YouError):
    r"""Internal Server Error during authentication/authorization middleware."""

    data: FinanceResearchInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: FinanceResearchInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FinanceResearchUnprocessableEntityErrorData(BaseModel):
    detail: Optional[List[models_finance_researchop.FinanceResearchDetail]] = None


@dataclass(unsafe_hash=True)
class FinanceResearchUnprocessableEntityError(YouError):
    r"""Unprocessable Entity. Request validation failed."""

    data: FinanceResearchUnprocessableEntityErrorData = field(hash=False)

    def __init__(
        self,
        data: FinanceResearchUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FinanceResearchForbiddenErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class FinanceResearchForbiddenError(YouError):
    r"""Forbidden. API key lacks scope for this path."""

    data: FinanceResearchForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: FinanceResearchForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class FinanceResearchUnauthorizedErrorData(BaseModel):
    detail: Optional[str] = None
    r"""Error detail message."""


@dataclass(unsafe_hash=True)
class FinanceResearchUnauthorizedError(YouError):
    r"""Unauthorized. Problems with API key."""

    data: FinanceResearchUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: FinanceResearchUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
