"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import List, Optional
from youdotcom.errors import YouError
from youdotcom.models import post_v1_agents_runsop as models_post_v1_agents_runsop
from youdotcom.types import BaseModel


class PostV1AgentsRunsForbiddenErrorData(BaseModel):
    errors: List[models_post_v1_agents_runsop.ForbiddenError]


@dataclass(unsafe_hash=True)
class PostV1AgentsRunsForbiddenError(YouError):
    r"""Forbidden. API key lacks scope for this path."""

    data: PostV1AgentsRunsForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV1AgentsRunsForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class PostV1AgentsRunsUnauthorizedErrorData(BaseModel):
    errors: List[models_post_v1_agents_runsop.UnauthorizedError]


@dataclass(unsafe_hash=True)
class PostV1AgentsRunsUnauthorizedError(YouError):
    r"""Unauthorized. Problems with API key."""

    data: PostV1AgentsRunsUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: PostV1AgentsRunsUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class BadRequestErrorData(BaseModel):
    errors: List[models_post_v1_agents_runsop.BadRequestError]


@dataclass(unsafe_hash=True)
class BadRequestError(YouError):
    r"""Bad Request. Invalid or malformed request body/parameters."""

    data: BadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: BadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
