"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import List, Optional
from youdotcom.errors import YouError
from youdotcom.models import researchop as models_researchop
from youdotcom.types import BaseModel


class ResearchInternalServerErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class ResearchInternalServerError(YouError):
    r"""Internal Server Error during authentication/authorization middleware."""

    data: ResearchInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: ResearchInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ResearchUnprocessableEntityErrorData(BaseModel):
    detail: Optional[List[models_researchop.ResearchDetail]] = None


@dataclass(unsafe_hash=True)
class ResearchUnprocessableEntityError(YouError):
    r"""Unprocessable Entity. Request validation failed."""

    data: ResearchUnprocessableEntityErrorData = field(hash=False)

    def __init__(
        self,
        data: ResearchUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ResearchForbiddenErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class ResearchForbiddenError(YouError):
    r"""Forbidden. API key lacks scope for this path."""

    data: ResearchForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: ResearchForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class ResearchUnauthorizedErrorData(BaseModel):
    detail: Optional[str] = None
    r"""Error detail message."""


@dataclass(unsafe_hash=True)
class ResearchUnauthorizedError(YouError):
    r"""Unauthorized. Problems with API key."""

    data: ResearchUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: ResearchUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
