"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import List, Optional
from youdotcom.errors import YouError
from youdotcom.models import (
    v1researchpostresponsescontentapplicationjsonschemadetailitems as models_v1researchpostresponsescontentapplicationjsonschemadetailitems,
)
from youdotcom.types import BaseModel


class ResearchRequestUnprocessableEntityErrorData(BaseModel):
    detail: Optional[
        List[
            models_v1researchpostresponsescontentapplicationjsonschemadetailitems.V1ResearchPostResponsesContentApplicationJSONSchemaDetailItems
        ]
    ] = None


@dataclass(unsafe_hash=True)
class ResearchRequestUnprocessableEntityError(YouError):
    data: ResearchRequestUnprocessableEntityErrorData = field(hash=False)

    def __init__(
        self,
        data: ResearchRequestUnprocessableEntityErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
