"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import Optional
from youdotcom.errors import YouError
from youdotcom.types import BaseModel


class SearchInternalServerErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class SearchInternalServerError(YouError):
    r"""Internal Server Error during authentication/authorization middleware."""

    data: SearchInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: SearchInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class SearchForbiddenErrorData(BaseModel):
    detail: Optional[str] = None


@dataclass(unsafe_hash=True)
class SearchForbiddenError(YouError):
    r"""Forbidden. API key lacks scope for this path."""

    data: SearchForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: SearchForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class SearchUnauthorizedErrorData(BaseModel):
    detail: Optional[str] = None
    r"""Error detail message."""


@dataclass(unsafe_hash=True)
class SearchUnauthorizedError(YouError):
    r"""Unauthorized. Problems with API key."""

    data: SearchUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: SearchUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
