"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from typing import Optional
from youdotcom.errors import YouError
from youdotcom.types import BaseModel


class UnauthorizedResponseErrorData(BaseModel):
    detail: Optional[str] = None
    r"""Error detail message."""


@dataclass(unsafe_hash=True)
class UnauthorizedResponseError(YouError):
    r"""Unauthorized. Problems with API key."""

    data: UnauthorizedResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: UnauthorizedResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
