"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from tests.test_client import create_test_http_client
from youdotcom import You


def test_search_get_v1_search():
    test_http_client = create_test_http_client("get_/v1/search")

    with You(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key_auth=os.getenv("YOU_API_KEY_AUTH", "value"),
    ) as you:
        assert you is not None

        res = you.search.unified(query="Your query")
        assert res is not None


def test_search_get_v1_search_insufficient_credits():
    test_http_client = create_test_http_client("get_/v1/search-insufficient_credits")

    with You(
        server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        client=test_http_client,
        api_key_auth=os.getenv("YOU_API_KEY_AUTH", "value"),
    ) as you:
        assert you is not None

        res = you.search.unified(query="Your query")
        assert res is not None
