"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from tests.test_client import create_test_http_client
from youdotcom import You


def test_runs_post_v1_agents_runs_insufficient_credits():
    test_http_client = create_test_http_client(
        "post_/v1/agents/runs-insufficient_credits"
    )

    with You(
        client=test_http_client,
        api_key_auth=os.getenv("YOU_API_KEY_AUTH", "value"),
    ) as you:
        assert you is not None

        res = you.agents.runs.create(
            agent="550e8400-e29b-41d4-a716-446655440000",
            input="Summarize today's top AI research headlines and cite sources.",
            stream=False,
            server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        )
        assert res is not None


def test_runs_post_v1_agents_runs():
    test_http_client = create_test_http_client("post_/v1/agents/runs")

    with You(
        client=test_http_client,
        api_key_auth=os.getenv("YOU_API_KEY_AUTH", "value"),
    ) as you:
        assert you is not None

        res = you.agents.runs.create(
            agent="<value>",
            input="<value>",
            stream=False,
            server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        )
        assert res is not None
