"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from tests.test_client import create_test_http_client
from youdotcom import You


def test_contents_post_v1_contents_insufficient_credits():
    test_http_client = create_test_http_client("post_/v1/contents-insufficient_credits")

    with You(
        client=test_http_client,
        api_key_auth=os.getenv("YOU_API_KEY_AUTH", "value"),
    ) as you:
        assert you is not None

        res = you.contents.generate(
            urls=[
                "https://www.you.com",
            ],
            format_="html",
            server_url=os.getenv("TEST_SERVER_URL", "http://localhost:18080"),
        )
        assert res is not None
