// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// AgentType - Built-in agent types
type AgentType string

const (
	AgentTypeExpress  AgentType = "express"
	AgentTypeAdvanced AgentType = "advanced"
)

func (e AgentType) ToPointer() *AgentType {
	return &e
}
func (e *AgentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "express":
		fallthrough
	case "advanced":
		*e = AgentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AgentType: %v", v)
	}
}
