// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ChatAnswerFullSource struct {
	URL   *string `json:"url,omitempty"`
	Title *string `json:"title,omitempty"`
}

func (c ChatAnswerFullSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatAnswerFullSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ChatAnswerFullSource) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *ChatAnswerFullSource) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

type ChatAnswerFull struct {
	type_   string                 `const:"message.answer" json:"type"`
	Text    *string                `json:"text,omitempty"`
	Sources []ChatAnswerFullSource `json:"sources,omitempty"`
}

func (c ChatAnswerFull) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ChatAnswerFull) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *ChatAnswerFull) GetType() string {
	return "message.answer"
}

func (o *ChatAnswerFull) GetText() *string {
	if o == nil {
		return nil
	}
	return o.Text
}

func (o *ChatAnswerFull) GetSources() []ChatAnswerFullSource {
	if o == nil {
		return nil
	}
	return o.Sources
}
