// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ComputeResultsFull struct {
	type_      string  `const:"compute.results" json:"type"`
	Result     *string `json:"result,omitempty"`
	Expression *string `json:"expression,omitempty"`
}

func (c ComputeResultsFull) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *ComputeResultsFull) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *ComputeResultsFull) GetType() string {
	return "compute.results"
}

func (o *ComputeResultsFull) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *ComputeResultsFull) GetExpression() *string {
	if o == nil {
		return nil
	}
	return o.Expression
}
