// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Country - The country code that determines the geographical focus of the web results.
type Country string

const (
	CountryAr Country = "AR"
	CountryAu Country = "AU"
	CountryAt Country = "AT"
	CountryBe Country = "BE"
	CountryBr Country = "BR"
	CountryCa Country = "CA"
	CountryCl Country = "CL"
	CountryDk Country = "DK"
	CountryFi Country = "FI"
	CountryFr Country = "FR"
	CountryDe Country = "DE"
	CountryHk Country = "HK"
	CountryIn Country = "IN"
	CountryId Country = "ID"
	CountryIt Country = "IT"
	CountryJp Country = "JP"
	CountryKr Country = "KR"
	CountryMy Country = "MY"
	CountryMx Country = "MX"
	CountryNl Country = "NL"
	CountryNz Country = "NZ"
	CountryNo Country = "NO"
	CountryCn Country = "CN"
	CountryPl Country = "PL"
	CountryPt Country = "PT"
	CountryPh Country = "PH"
	CountryRu Country = "RU"
	CountrySa Country = "SA"
	CountryZa Country = "ZA"
	CountryEs Country = "ES"
	CountrySe Country = "SE"
	CountryCh Country = "CH"
	CountryTw Country = "TW"
	CountryTr Country = "TR"
	CountryGb Country = "GB"
	CountryUs Country = "US"
)

func (e Country) ToPointer() *Country {
	return &e
}
func (e *Country) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AR":
		fallthrough
	case "AU":
		fallthrough
	case "AT":
		fallthrough
	case "BE":
		fallthrough
	case "BR":
		fallthrough
	case "CA":
		fallthrough
	case "CL":
		fallthrough
	case "DK":
		fallthrough
	case "FI":
		fallthrough
	case "FR":
		fallthrough
	case "DE":
		fallthrough
	case "HK":
		fallthrough
	case "IN":
		fallthrough
	case "ID":
		fallthrough
	case "IT":
		fallthrough
	case "JP":
		fallthrough
	case "KR":
		fallthrough
	case "MY":
		fallthrough
	case "MX":
		fallthrough
	case "NL":
		fallthrough
	case "NZ":
		fallthrough
	case "NO":
		fallthrough
	case "CN":
		fallthrough
	case "PL":
		fallthrough
	case "PT":
		fallthrough
	case "PH":
		fallthrough
	case "RU":
		fallthrough
	case "SA":
		fallthrough
	case "ZA":
		fallthrough
	case "ES":
		fallthrough
	case "SE":
		fallthrough
	case "CH":
		fallthrough
	case "TW":
		fallthrough
	case "TR":
		fallthrough
	case "GB":
		fallthrough
	case "US":
		*e = Country(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Country: %v", v)
	}
}
