// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Freshness - Specifies the freshness of the results to return.
type Freshness string

const (
	FreshnessDay   Freshness = "day"
	FreshnessWeek  Freshness = "week"
	FreshnessMonth Freshness = "month"
	FreshnessYear  Freshness = "year"
)

func (e Freshness) ToPointer() *Freshness {
	return &e
}
func (e *Freshness) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "day":
		fallthrough
	case "week":
		fallthrough
	case "month":
		fallthrough
	case "year":
		*e = Freshness(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Freshness: %v", v)
	}
}
