// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/utils"
)

type FullResponseType string

const (
	FullResponseTypeWebSearchResultsFull FullResponseType = "WebSearchResultsFull"
	FullResponseTypeChatAnswerFull       FullResponseType = "ChatAnswerFull"
	FullResponseTypeResearchResultsFull  FullResponseType = "ResearchResultsFull"
	FullResponseTypeComputeResultsFull   FullResponseType = "ComputeResultsFull"
	FullResponseTypeLiveCrawlResultsFull FullResponseType = "LiveCrawlResultsFull"
	FullResponseTypeGenericFull          FullResponseType = "GenericFull"
	FullResponseTypeArrayOfMapOfAny      FullResponseType = "arrayOfMapOfAny"
)

type FullResponse struct {
	WebSearchResultsFull *WebSearchResultsFull `queryParam:"inline"`
	ChatAnswerFull       *ChatAnswerFull       `queryParam:"inline"`
	ResearchResultsFull  *ResearchResultsFull  `queryParam:"inline"`
	ComputeResultsFull   *ComputeResultsFull   `queryParam:"inline"`
	LiveCrawlResultsFull *LiveCrawlResultsFull `queryParam:"inline"`
	GenericFull          *GenericFull          `queryParam:"inline"`
	ArrayOfMapOfAny      []map[string]any      `queryParam:"inline"`

	Type FullResponseType
}

func CreateFullResponseWebSearchResultsFull(webSearchResultsFull WebSearchResultsFull) FullResponse {
	typ := FullResponseTypeWebSearchResultsFull

	return FullResponse{
		WebSearchResultsFull: &webSearchResultsFull,
		Type:                 typ,
	}
}

func CreateFullResponseChatAnswerFull(chatAnswerFull ChatAnswerFull) FullResponse {
	typ := FullResponseTypeChatAnswerFull

	return FullResponse{
		ChatAnswerFull: &chatAnswerFull,
		Type:           typ,
	}
}

func CreateFullResponseResearchResultsFull(researchResultsFull ResearchResultsFull) FullResponse {
	typ := FullResponseTypeResearchResultsFull

	return FullResponse{
		ResearchResultsFull: &researchResultsFull,
		Type:                typ,
	}
}

func CreateFullResponseComputeResultsFull(computeResultsFull ComputeResultsFull) FullResponse {
	typ := FullResponseTypeComputeResultsFull

	return FullResponse{
		ComputeResultsFull: &computeResultsFull,
		Type:               typ,
	}
}

func CreateFullResponseLiveCrawlResultsFull(liveCrawlResultsFull LiveCrawlResultsFull) FullResponse {
	typ := FullResponseTypeLiveCrawlResultsFull

	return FullResponse{
		LiveCrawlResultsFull: &liveCrawlResultsFull,
		Type:                 typ,
	}
}

func CreateFullResponseGenericFull(genericFull GenericFull) FullResponse {
	typ := FullResponseTypeGenericFull

	return FullResponse{
		GenericFull: &genericFull,
		Type:        typ,
	}
}

func CreateFullResponseArrayOfMapOfAny(arrayOfMapOfAny []map[string]any) FullResponse {
	typ := FullResponseTypeArrayOfMapOfAny

	return FullResponse{
		ArrayOfMapOfAny: arrayOfMapOfAny,
		Type:            typ,
	}
}

func (u *FullResponse) UnmarshalJSON(data []byte) error {

	var webSearchResultsFull WebSearchResultsFull = WebSearchResultsFull{}
	if err := utils.UnmarshalJSON(data, &webSearchResultsFull, "", true, nil); err == nil {
		u.WebSearchResultsFull = &webSearchResultsFull
		u.Type = FullResponseTypeWebSearchResultsFull
		return nil
	}

	var chatAnswerFull ChatAnswerFull = ChatAnswerFull{}
	if err := utils.UnmarshalJSON(data, &chatAnswerFull, "", true, nil); err == nil {
		u.ChatAnswerFull = &chatAnswerFull
		u.Type = FullResponseTypeChatAnswerFull
		return nil
	}

	var researchResultsFull ResearchResultsFull = ResearchResultsFull{}
	if err := utils.UnmarshalJSON(data, &researchResultsFull, "", true, nil); err == nil {
		u.ResearchResultsFull = &researchResultsFull
		u.Type = FullResponseTypeResearchResultsFull
		return nil
	}

	var computeResultsFull ComputeResultsFull = ComputeResultsFull{}
	if err := utils.UnmarshalJSON(data, &computeResultsFull, "", true, nil); err == nil {
		u.ComputeResultsFull = &computeResultsFull
		u.Type = FullResponseTypeComputeResultsFull
		return nil
	}

	var liveCrawlResultsFull LiveCrawlResultsFull = LiveCrawlResultsFull{}
	if err := utils.UnmarshalJSON(data, &liveCrawlResultsFull, "", true, nil); err == nil {
		u.LiveCrawlResultsFull = &liveCrawlResultsFull
		u.Type = FullResponseTypeLiveCrawlResultsFull
		return nil
	}

	var genericFull GenericFull = GenericFull{}
	if err := utils.UnmarshalJSON(data, &genericFull, "", true, nil); err == nil {
		u.GenericFull = &genericFull
		u.Type = FullResponseTypeGenericFull
		return nil
	}

	var arrayOfMapOfAny []map[string]any = []map[string]any{}
	if err := utils.UnmarshalJSON(data, &arrayOfMapOfAny, "", true, nil); err == nil {
		u.ArrayOfMapOfAny = arrayOfMapOfAny
		u.Type = FullResponseTypeArrayOfMapOfAny
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for FullResponse", string(data))
}

func (u FullResponse) MarshalJSON() ([]byte, error) {
	if u.WebSearchResultsFull != nil {
		return utils.MarshalJSON(u.WebSearchResultsFull, "", true)
	}

	if u.ChatAnswerFull != nil {
		return utils.MarshalJSON(u.ChatAnswerFull, "", true)
	}

	if u.ResearchResultsFull != nil {
		return utils.MarshalJSON(u.ResearchResultsFull, "", true)
	}

	if u.ComputeResultsFull != nil {
		return utils.MarshalJSON(u.ComputeResultsFull, "", true)
	}

	if u.LiveCrawlResultsFull != nil {
		return utils.MarshalJSON(u.LiveCrawlResultsFull, "", true)
	}

	if u.GenericFull != nil {
		return utils.MarshalJSON(u.GenericFull, "", true)
	}

	if u.ArrayOfMapOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfMapOfAny, "", true)
	}

	return nil, errors.New("could not marshal union type FullResponse: all fields are null")
}
