// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// LiveCrawl - Indicates which section(s) of search results to livecrawl and return full page content.
type LiveCrawl string

const (
	LiveCrawlWeb  LiveCrawl = "web"
	LiveCrawlNews LiveCrawl = "news"
	LiveCrawlAll  LiveCrawl = "all"
)

func (e LiveCrawl) ToPointer() *LiveCrawl {
	return &e
}
func (e *LiveCrawl) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "web":
		fallthrough
	case "news":
		fallthrough
	case "all":
		*e = LiveCrawl(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LiveCrawl: %v", v)
	}
}
