// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// LiveCrawlFormats - Indicates the format of the livecrawled content.
type LiveCrawlFormats string

const (
	LiveCrawlFormatsHtml     LiveCrawlFormats = "html"
	LiveCrawlFormatsMarkdown LiveCrawlFormats = "markdown"
)

func (e LiveCrawlFormats) ToPointer() *LiveCrawlFormats {
	return &e
}
func (e *LiveCrawlFormats) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "html":
		fallthrough
	case "markdown":
		*e = LiveCrawlFormats(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LiveCrawlFormats: %v", v)
	}
}
