// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type LiveCrawlResultsFull struct {
	type_   string         `const:"live_crawl.results" json:"type"`
	Content map[string]any `json:"content,omitempty"`
	URL     *string        `json:"url,omitempty"`
}

func (l LiveCrawlResultsFull) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LiveCrawlResultsFull) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *LiveCrawlResultsFull) GetType() string {
	return "live_crawl.results"
}

func (o *LiveCrawlResultsFull) GetContent() map[string]any {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *LiveCrawlResultsFull) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}
