// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type ResearchResultsFullSource struct {
	URL     *string `json:"url,omitempty"`
	Title   *string `json:"title,omitempty"`
	Snippet *string `json:"snippet,omitempty"`
}

func (r ResearchResultsFullSource) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResearchResultsFullSource) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *ResearchResultsFullSource) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *ResearchResultsFullSource) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *ResearchResultsFullSource) GetSnippet() *string {
	if o == nil {
		return nil
	}
	return o.Snippet
}

type ResearchResultsFull struct {
	type_   string                      `const:"research.results" json:"type"`
	Report  *string                     `json:"report,omitempty"`
	Sources []ResearchResultsFullSource `json:"sources,omitempty"`
}

func (r ResearchResultsFull) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ResearchResultsFull) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *ResearchResultsFull) GetType() string {
	return "research.results"
}

func (o *ResearchResultsFull) GetReport() *string {
	if o == nil {
		return nil
	}
	return o.Report
}

func (o *ResearchResultsFull) GetSources() []ResearchResultsFullSource {
	if o == nil {
		return nil
	}
	return o.Sources
}
