// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Trigger - Tool trigger mode: 'intent' lets agent decide, 'force' always uses the tool
type Trigger string

const (
	TriggerIntent Trigger = "intent"
	TriggerForce  Trigger = "force"
)

func (e Trigger) ToPointer() *Trigger {
	return &e
}
func (e *Trigger) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "intent":
		fallthrough
	case "force":
		*e = Trigger(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Trigger: %v", v)
	}
}
