// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"encoding/json"
	"fmt"
)

// Verbosity - Response verbosity level
type Verbosity string

const (
	VerbosityLow    Verbosity = "low"
	VerbosityMedium Verbosity = "medium"
	VerbosityHigh   Verbosity = "high"
)

func (e Verbosity) ToPointer() *Verbosity {
	return &e
}
func (e *Verbosity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "low":
		fallthrough
	case "medium":
		fallthrough
	case "high":
		*e = Verbosity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Verbosity: %v", v)
	}
}
