// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

type Result struct {
	URL         *string `json:"url,omitempty"`
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Age         *string `json:"age,omitempty"`
}

func (r Result) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *Result) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *Result) GetURL() *string {
	if o == nil {
		return nil
	}
	return o.URL
}

func (o *Result) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *Result) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *Result) GetAge() *string {
	if o == nil {
		return nil
	}
	return o.Age
}

type WebSearchResultsFull struct {
	type_   string   `const:"web_search.results" json:"type"`
	Results []Result `json:"results,omitempty"`
}

func (w WebSearchResultsFull) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebSearchResultsFull) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *WebSearchResultsFull) GetType() string {
	return "web_search.results"
}

func (o *WebSearchResultsFull) GetResults() []Result {
	if o == nil {
		return nil
	}
	return o.Results
}
