// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package components

import (
	"mockserver/internal/sdk/utils"
)

// WebSearchTool - Web search tool with optional intent-based triggering
type WebSearchTool struct {
	type_ string `const:"web_search" json:"type"`
	// Tool trigger mode: 'intent' lets agent decide, 'force' always uses the tool
	Trigger *Trigger `json:"trigger,omitempty"`
}

func (w WebSearchTool) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WebSearchTool) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, []string{"type"}); err != nil {
		return err
	}
	return nil
}

func (o *WebSearchTool) GetType() string {
	return "web_search"
}

func (o *WebSearchTool) GetTrigger() *Trigger {
	if o == nil {
		return nil
	}
	return o.Trigger
}
