// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/types/stream"
	"mockserver/internal/sdk/utils"
)

type AgentType string

const (
	AgentTypeAgentType AgentType = "AgentType"
	AgentTypeStr       AgentType = "str"
)

// Agent type (express, advanced) or custom agent UUID
type Agent struct {
	AgentType *components.AgentType `queryParam:"inline"`
	Str       *string               `queryParam:"inline"`

	Type AgentType
}

func CreateAgentAgentType(agentType components.AgentType) Agent {
	typ := AgentTypeAgentType

	return Agent{
		AgentType: &agentType,
		Type:      typ,
	}
}

func CreateAgentStr(str string) Agent {
	typ := AgentTypeStr

	return Agent{
		Str:  &str,
		Type: typ,
	}
}

func (u *Agent) UnmarshalJSON(data []byte) error {

	var agentType components.AgentType = components.AgentType("")
	if err := utils.UnmarshalJSON(data, &agentType, "", true, nil); err == nil {
		u.AgentType = &agentType
		u.Type = AgentTypeAgentType
		return nil
	}

	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		u.Str = &str
		u.Type = AgentTypeStr
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Agent", string(data))
}

func (u Agent) MarshalJSON() ([]byte, error) {
	if u.AgentType != nil {
		return utils.MarshalJSON(u.AgentType, "", true)
	}

	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	return nil, errors.New("could not marshal union type Agent: all fields are null")
}

type WorkflowConfig struct {
	// Maximum number of workflow steps
	MaxWorkflowSteps *int64 `default:"5" json:"max_workflow_steps"`
}

func (w WorkflowConfig) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkflowConfig) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (o *WorkflowConfig) GetMaxWorkflowSteps() *int64 {
	if o == nil {
		return nil
	}
	return o.MaxWorkflowSteps
}

type PostV1AgentsRunsRequest struct {
	// Agent type (express, advanced) or custom agent UUID
	Agent Agent `json:"agent"`
	// User input prompt.
	Input  string `json:"input"`
	Stream *bool  `default:"false" json:"stream"`
	// Array of tool configurations
	Tools []components.Tool `json:"tools,omitempty"`
	// Response verbosity level
	Verbosity      *components.Verbosity `json:"verbosity,omitempty"`
	WorkflowConfig *WorkflowConfig       `json:"workflow_config,omitempty"`
}

func (p PostV1AgentsRunsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *PostV1AgentsRunsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"agent", "input"}); err != nil {
		return err
	}
	return nil
}

func (o *PostV1AgentsRunsRequest) GetAgent() Agent {
	if o == nil {
		return Agent{}
	}
	return o.Agent
}

func (o *PostV1AgentsRunsRequest) GetInput() string {
	if o == nil {
		return ""
	}
	return o.Input
}

func (o *PostV1AgentsRunsRequest) GetStream() *bool {
	if o == nil {
		return nil
	}
	return o.Stream
}

func (o *PostV1AgentsRunsRequest) GetTools() []components.Tool {
	if o == nil {
		return nil
	}
	return o.Tools
}

func (o *PostV1AgentsRunsRequest) GetVerbosity() *components.Verbosity {
	if o == nil {
		return nil
	}
	return o.Verbosity
}

func (o *PostV1AgentsRunsRequest) GetWorkflowConfig() *WorkflowConfig {
	if o == nil {
		return nil
	}
	return o.WorkflowConfig
}

type ForbiddenError struct {
	Status string `json:"status"`
	Code   string `json:"code"`
	Title  string `json:"title"`
	Detail string `json:"detail"`
}

func (o *ForbiddenError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *ForbiddenError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *ForbiddenError) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *ForbiddenError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

type UnauthorizedError struct {
	Status string `json:"status"`
	Code   string `json:"code"`
	Title  string `json:"title"`
	Detail string `json:"detail"`
}

func (o *UnauthorizedError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *UnauthorizedError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *UnauthorizedError) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *UnauthorizedError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

type BadRequestError struct {
	Status string `json:"status"`
	Code   string `json:"code"`
	Title  string `json:"title"`
	Detail string `json:"detail"`
}

func (o *BadRequestError) GetStatus() string {
	if o == nil {
		return ""
	}
	return o.Status
}

func (o *BadRequestError) GetCode() string {
	if o == nil {
		return ""
	}
	return o.Code
}

func (o *BadRequestError) GetTitle() string {
	if o == nil {
		return ""
	}
	return o.Title
}

func (o *BadRequestError) GetDetail() string {
	if o == nil {
		return ""
	}
	return o.Detail
}

type Response struct {
	// The type of the response.
	Type *string `json:"type,omitempty"`
	// The index of the output in the response.
	OutputIndex *int64 `json:"output_index,omitempty"`
	// The delta of the response.
	Delta *string                  `json:"delta,omitempty"`
	Full  *components.FullResponse `json:"full,omitempty"`
}

func (o *Response) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Response) GetOutputIndex() *int64 {
	if o == nil {
		return nil
	}
	return o.OutputIndex
}

func (o *Response) GetDelta() *string {
	if o == nil {
		return nil
	}
	return o.Delta
}

func (o *Response) GetFull() *components.FullResponse {
	if o == nil {
		return nil
	}
	return o.Full
}

type Data struct {
	// Sequence number of the SSE event, starts from 0. Same as `id` field.
	SeqID *int64 `json:"seq_id,omitempty"`
	// The type of the SSE event. Same as `event` field.
	Type     *string   `json:"type,omitempty"`
	Response *Response `json:"response,omitempty"`
}

func (o *Data) GetSeqID() *int64 {
	if o == nil {
		return nil
	}
	return o.SeqID
}

func (o *Data) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Data) GetResponse() *Response {
	if o == nil {
		return nil
	}
	return o.Response
}

// PostV1AgentsRunsEventStreamResponseBody - Inference response in application/json or text/event-stream format.
type PostV1AgentsRunsEventStreamResponseBody struct {
	// Sequence number of the SSE event
	ID *string `json:"id,omitempty"`
	// The type of the SSE event.
	Event *string `json:"event,omitempty"`
	Data  *Data   `json:"data,omitempty"`
}

func (o *PostV1AgentsRunsEventStreamResponseBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PostV1AgentsRunsEventStreamResponseBody) GetEvent() *string {
	if o == nil {
		return nil
	}
	return o.Event
}

func (o *PostV1AgentsRunsEventStreamResponseBody) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o PostV1AgentsRunsEventStreamResponseBody) GetEventEncoding(event string) (string, error) {
	return "application/json", nil
}

type Content struct {
}

func (c Content) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Content) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

type ContentUnion1Type string

const (
	ContentUnion1TypeArrayOfAny ContentUnion1Type = "arrayOfAny"
	ContentUnion1TypeContent    ContentUnion1Type = "content"
)

type ContentUnion1 struct {
	ArrayOfAny []any    `queryParam:"inline"`
	Content    *Content `queryParam:"inline"`

	Type ContentUnion1Type
}

func CreateContentUnion1ArrayOfAny(arrayOfAny []any) ContentUnion1 {
	typ := ContentUnion1TypeArrayOfAny

	return ContentUnion1{
		ArrayOfAny: arrayOfAny,
		Type:       typ,
	}
}

func CreateContentUnion1Content(content Content) ContentUnion1 {
	typ := ContentUnion1TypeContent

	return ContentUnion1{
		Content: &content,
		Type:    typ,
	}
}

func (u *ContentUnion1) UnmarshalJSON(data []byte) error {

	var arrayOfAny []any = []any{}
	if err := utils.UnmarshalJSON(data, &arrayOfAny, "", true, nil); err == nil {
		u.ArrayOfAny = arrayOfAny
		u.Type = ContentUnion1TypeArrayOfAny
		return nil
	}

	var content Content = Content{}
	if err := utils.UnmarshalJSON(data, &content, "", true, nil); err == nil {
		u.Content = &content
		u.Type = ContentUnion1TypeContent
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ContentUnion1", string(data))
}

func (u ContentUnion1) MarshalJSON() ([]byte, error) {
	if u.ArrayOfAny != nil {
		return utils.MarshalJSON(u.ArrayOfAny, "", true)
	}

	if u.Content != nil {
		return utils.MarshalJSON(u.Content, "", true)
	}

	return nil, errors.New("could not marshal union type ContentUnion1: all fields are null")
}

type ContentUnion2Type string

const (
	ContentUnion2TypeMapOfAny      ContentUnion2Type = "mapOfAny"
	ContentUnion2TypeContentUnion1 ContentUnion2Type = "content_union_1"
)

// ContentUnion2 - Returns the exact search query or list of sources.
type ContentUnion2 struct {
	MapOfAny      map[string]any `queryParam:"inline"`
	ContentUnion1 *ContentUnion1 `queryParam:"inline"`

	Type ContentUnion2Type
}

func CreateContentUnion2MapOfAny(mapOfAny map[string]any) ContentUnion2 {
	typ := ContentUnion2TypeMapOfAny

	return ContentUnion2{
		MapOfAny: mapOfAny,
		Type:     typ,
	}
}

func CreateContentUnion2ContentUnion1(contentUnion1 ContentUnion1) ContentUnion2 {
	typ := ContentUnion2TypeContentUnion1

	return ContentUnion2{
		ContentUnion1: &contentUnion1,
		Type:          typ,
	}
}

func (u *ContentUnion2) UnmarshalJSON(data []byte) error {

	var mapOfAny map[string]any = map[string]any{}
	if err := utils.UnmarshalJSON(data, &mapOfAny, "", true, nil); err == nil {
		u.MapOfAny = mapOfAny
		u.Type = ContentUnion2TypeMapOfAny
		return nil
	}

	var contentUnion1 ContentUnion1 = ContentUnion1{}
	if err := utils.UnmarshalJSON(data, &contentUnion1, "", true, nil); err == nil {
		u.ContentUnion1 = &contentUnion1
		u.Type = ContentUnion2TypeContentUnion1
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for ContentUnion2", string(data))
}

func (u ContentUnion2) MarshalJSON() ([]byte, error) {
	if u.MapOfAny != nil {
		return utils.MarshalJSON(u.MapOfAny, "", true)
	}

	if u.ContentUnion1 != nil {
		return utils.MarshalJSON(u.ContentUnion1, "", true)
	}

	return nil, errors.New("could not marshal union type ContentUnion2: all fields are null")
}

type Output struct {
	// The type of the output.
	Type *string `json:"type,omitempty"`
	// The text of the output.
	Text *string `json:"text,omitempty"`
	// Returns the exact search query or list of sources.
	Content *ContentUnion2 `json:"content,omitempty"`
	// The agent used to generate the response.
	Agent *string `json:"agent,omitempty"`
}

func (o *Output) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *Output) GetText() *string {
	if o == nil {
		return nil
	}
	return o.Text
}

func (o *Output) GetContent() *ContentUnion2 {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *Output) GetAgent() *string {
	if o == nil {
		return nil
	}
	return o.Agent
}

// PostV1AgentsRunsResponseBody - Inference response in application/json or text/event-stream format.
type PostV1AgentsRunsResponseBody struct {
	Output []Output `json:"output,omitempty"`
}

func (o *PostV1AgentsRunsResponseBody) GetOutput() []Output {
	if o == nil {
		return nil
	}
	return o.Output
}

type PostV1AgentsRunsResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Inference response in application/json or text/event-stream format.
	TwoHundredApplicationJSONObject *PostV1AgentsRunsResponseBody
	// Inference response in application/json or text/event-stream format.
	TwoHundredTextEventStreamObject *stream.EventStream[PostV1AgentsRunsEventStreamResponseBody]
}

func (o *PostV1AgentsRunsResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *PostV1AgentsRunsResponse) GetTwoHundredApplicationJSONObject() *PostV1AgentsRunsResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PostV1AgentsRunsResponse) GetTwoHundredTextEventStreamObject() *stream.EventStream[PostV1AgentsRunsEventStreamResponseBody] {
	if o == nil {
		return nil
	}
	return o.TwoHundredTextEventStreamObject
}
