"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from enum import Enum
from typing import Any, List, Literal, Mapping, Optional, Union, overload
from youdotcom import errors, models, utils
from youdotcom._hooks import HookContext
from youdotcom.types import OptionalNullable, UNSET
from youdotcom.utils import eventstreaming, get_security_from_env
from youdotcom.utils.unmarshal_json_response import unmarshal_json_response


class CreateAcceptEnum(str, Enum):
    APPLICATION_JSON = "application/json"
    TEXT_EVENT_STREAM = "text/event-stream"


class Runs(BaseSDK):
    @overload
    def create(
        self,
        *,
        agent: Union[models.Agent, models.AgentTypedDict],
        input: str,
        stream: Union[Literal[False], None] = None,
        tools: Optional[Union[List[models.Tool], List[models.ToolTypedDict]]] = None,
        verbosity: Optional[models.Verbosity] = None,
        workflow_config: Optional[
            Union[models.WorkflowConfig, models.WorkflowConfigTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV1AgentsRunsResponseBody:
        r"""
        :param agent: Agent type (express, advanced) or custom agent UUID
        :param input: User input prompt.
        :param stream:
        :param tools: Array of tool configurations
        :param verbosity: Response verbosity level
        :param workflow_config:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """

    @overload
    def create(
        self,
        *,
        agent: Union[models.Agent, models.AgentTypedDict],
        input: str,
        stream: Literal[True],
        tools: Optional[Union[List[models.Tool], List[models.ToolTypedDict]]] = None,
        verbosity: Optional[models.Verbosity] = None,
        workflow_config: Optional[
            Union[models.WorkflowConfig, models.WorkflowConfigTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> eventstreaming.EventStream[models.Data]:
        r"""
        :param agent: Agent type (express, advanced) or custom agent UUID
        :param input: User input prompt.
        :param stream:
        :param tools: Array of tool configurations
        :param verbosity: Response verbosity level
        :param workflow_config:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """

    def create(
        self,
        *,
        agent: Union[models.Agent, models.AgentTypedDict],
        input: str,
        stream: Optional[bool] = False,
        tools: Optional[Union[List[models.Tool], List[models.ToolTypedDict]]] = None,
        verbosity: Optional[models.Verbosity] = None,
        workflow_config: Optional[
            Union[models.WorkflowConfig, models.WorkflowConfigTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV1AgentsRunsResponse:
        r"""
        :param agent: Agent type (express, advanced) or custom agent UUID
        :param input: User input prompt.
        :param stream:
        :param tools: Array of tool configurations
        :param verbosity: Response verbosity level
        :param workflow_config:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.POST_V1_AGENTS_RUNS_OP_SERVERS[0]

        request = models.PostV1AgentsRunsRequest(
            agent=agent,
            input=input,
            stream=stream,
            tools=utils.get_pydantic_model(tools, Optional[List[models.Tool]]),
            verbosity=verbosity,
            workflow_config=utils.get_pydantic_model(
                workflow_config, Optional[models.WorkflowConfig]
            ),
        )

        req = self._build_request(
            method="POST",
            path="/v1/agents/runs",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="text/event-stream" if stream else "application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.PostV1AgentsRunsRequest
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/v1/agents/runs",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "5XX"],
            stream=True,
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            return unmarshal_json_response(
                models.PostV1AgentsRunsResponseBody, http_res, http_res_text
            )
        if utils.match_response(http_res, "200", "text/event-stream"):
            return eventstreaming.EventStream(
                http_res,
                lambda raw: utils.unmarshal_json(
                    raw, models.PostV1AgentsRunsEventStreamResponseBody
                ).data,
                client_ref=self,
            )
        if utils.match_response(http_res, "400", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            response_data = unmarshal_json_response(
                errors.BadRequestErrorData, http_res, http_res_text
            )
            raise errors.BadRequestError(response_data, http_res, http_res_text)
        if utils.match_response(http_res, "401", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            response_data = unmarshal_json_response(
                errors.PostV1AgentsRunsUnauthorizedErrorData, http_res, http_res_text
            )
            raise errors.PostV1AgentsRunsUnauthorizedError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "403", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            response_data = unmarshal_json_response(
                errors.PostV1AgentsRunsForbiddenErrorData, http_res, http_res_text
            )
            raise errors.PostV1AgentsRunsForbiddenError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)

        http_res_text = utils.stream_to_text(http_res)
        raise errors.YouDefaultError(
            "Unexpected response received", http_res, http_res_text
        )

    @overload
    async def create_async(
        self,
        *,
        agent: Union[models.Agent, models.AgentTypedDict],
        input: str,
        stream: Union[Literal[False], None] = None,
        tools: Optional[Union[List[models.Tool], List[models.ToolTypedDict]]] = None,
        verbosity: Optional[models.Verbosity] = None,
        workflow_config: Optional[
            Union[models.WorkflowConfig, models.WorkflowConfigTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV1AgentsRunsResponseBody:
        r"""
        :param agent: Agent type (express, advanced) or custom agent UUID
        :param input: User input prompt.
        :param stream:
        :param tools: Array of tool configurations
        :param verbosity: Response verbosity level
        :param workflow_config:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """

    @overload
    async def create_async(
        self,
        *,
        agent: Union[models.Agent, models.AgentTypedDict],
        input: str,
        stream: Literal[True],
        tools: Optional[Union[List[models.Tool], List[models.ToolTypedDict]]] = None,
        verbosity: Optional[models.Verbosity] = None,
        workflow_config: Optional[
            Union[models.WorkflowConfig, models.WorkflowConfigTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> eventstreaming.EventStreamAsync[models.Data]:
        r"""
        :param agent: Agent type (express, advanced) or custom agent UUID
        :param input: User input prompt.
        :param stream:
        :param tools: Array of tool configurations
        :param verbosity: Response verbosity level
        :param workflow_config:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """

    async def create_async(
        self,
        *,
        agent: Union[models.Agent, models.AgentTypedDict],
        input: str,
        stream: Optional[bool] = False,
        tools: Optional[Union[List[models.Tool], List[models.ToolTypedDict]]] = None,
        verbosity: Optional[models.Verbosity] = None,
        workflow_config: Optional[
            Union[models.WorkflowConfig, models.WorkflowConfigTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.PostV1AgentsRunsResponse:
        r"""
        :param agent: Agent type (express, advanced) or custom agent UUID
        :param input: User input prompt.
        :param stream:
        :param tools: Array of tool configurations
        :param verbosity: Response verbosity level
        :param workflow_config:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.POST_V1_AGENTS_RUNS_OP_SERVERS[0]

        request = models.PostV1AgentsRunsRequest(
            agent=agent,
            input=input,
            stream=stream,
            tools=utils.get_pydantic_model(tools, Optional[List[models.Tool]]),
            verbosity=verbosity,
            workflow_config=utils.get_pydantic_model(
                workflow_config, Optional[models.WorkflowConfig]
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/v1/agents/runs",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="text/event-stream" if stream else "application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.PostV1AgentsRunsRequest
            ),
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="post_/v1/agents/runs",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "5XX"],
            stream=True,
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            return unmarshal_json_response(
                models.PostV1AgentsRunsResponseBody, http_res, http_res_text
            )
        if utils.match_response(http_res, "200", "text/event-stream"):
            return eventstreaming.EventStreamAsync(
                http_res,
                lambda raw: utils.unmarshal_json(
                    raw, models.PostV1AgentsRunsEventStreamResponseBody
                ).data,
                client_ref=self,
            )
        if utils.match_response(http_res, "400", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            response_data = unmarshal_json_response(
                errors.BadRequestErrorData, http_res, http_res_text
            )
            raise errors.BadRequestError(response_data, http_res, http_res_text)
        if utils.match_response(http_res, "401", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            response_data = unmarshal_json_response(
                errors.PostV1AgentsRunsUnauthorizedErrorData, http_res, http_res_text
            )
            raise errors.PostV1AgentsRunsUnauthorizedError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "403", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            response_data = unmarshal_json_response(
                errors.PostV1AgentsRunsForbiddenErrorData, http_res, http_res_text
            )
            raise errors.PostV1AgentsRunsForbiddenError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)

        http_res_text = await utils.stream_to_text_async(http_res)
        raise errors.YouDefaultError(
            "Unexpected response received", http_res, http_res_text
        )
