"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from enum import Enum
from typing import Any, Mapping, Optional, Union, cast
from youdotcom import errors, models, utils
from youdotcom._hooks import HookContext
from youdotcom.types import BaseModel, OptionalNullable, UNSET
from youdotcom.utils import eventstreaming, get_security_from_env
from youdotcom.utils.unmarshal_json_response import unmarshal_json_response


class CreateAcceptEnum(str, Enum):
    APPLICATION_JSON = "application/json"
    TEXT_EVENT_STREAM = "text/event-stream"


class Runs(BaseSDK):
    def create(
        self,
        *,
        request: Union[models.AgentsRunsRequest, models.AgentsRunsRequestTypedDict],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        accept_header_override: Optional[CreateAcceptEnum] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AgentsRunsResponse:
        r"""Run an Agent

        Execute queries using You.com's AI agents. This endpoint supports three agent types:

        - **Express Agent**: Fast responses with optional web search (max 1 search)
        - **Advanced Agent**: Complex queries with multi-turn reasoning, planning, and tool usage
        - **Custom Agent**: User-configured assistants created in the You.com UI

        The response format depends on the `stream` parameter - either a complete JSON payload or Server-Sent Events (SSE).


        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.AGENTS_RUNS_OP_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, models.AgentsRunsRequest)
        request = cast(models.AgentsRunsRequest, request)

        req = self._build_request(
            method="POST",
            path="/v1/agents/runs",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=accept_header_override.value
            if accept_header_override is not None
            else "application/json;q=1, text/event-stream;q=0",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.AgentsRunsRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AgentsRuns",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "422", "4XX", "5XX"],
            stream=True,
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            return unmarshal_json_response(
                models.AgentRunsBatchResponse, http_res, http_res_text
            )
        if utils.match_response(http_res, "200", "text/event-stream"):
            return eventstreaming.EventStream(
                http_res,
                lambda raw: utils.unmarshal_json(
                    raw, models.AgentRunsStreamingResponse
                ),
                client_ref=self,
            )
        if utils.match_response(http_res, "400", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            response_data = unmarshal_json_response(
                errors.AgentRuns400ResponseErrorData, http_res, http_res_text
            )
            raise errors.AgentRuns400ResponseError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "401", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            response_data = unmarshal_json_response(
                errors.AgentRuns401ResponseErrorData, http_res, http_res_text
            )
            raise errors.AgentRuns401ResponseError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "422", "application/json"):
            http_res_text = utils.stream_to_text(http_res)
            response_data = unmarshal_json_response(
                errors.AgentRuns422ResponseErrorData, http_res, http_res_text
            )
            raise errors.AgentRuns422ResponseError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)

        http_res_text = utils.stream_to_text(http_res)
        raise errors.YouDefaultError(
            "Unexpected response received", http_res, http_res_text
        )

    async def create_async(
        self,
        *,
        request: Union[models.AgentsRunsRequest, models.AgentsRunsRequestTypedDict],
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        accept_header_override: Optional[CreateAcceptEnum] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.AgentsRunsResponse:
        r"""Run an Agent

        Execute queries using You.com's AI agents. This endpoint supports three agent types:

        - **Express Agent**: Fast responses with optional web search (max 1 search)
        - **Advanced Agent**: Complex queries with multi-turn reasoning, planning, and tool usage
        - **Custom Agent**: User-configured assistants created in the You.com UI

        The response format depends on the `stream` parameter - either a complete JSON payload or Server-Sent Events (SSE).


        :param request: The request object to send.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param accept_header_override: Override the default accept header for this method
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.AGENTS_RUNS_OP_SERVERS[0]

        if not isinstance(request, BaseModel):
            request = utils.unmarshal(request, models.AgentsRunsRequest)
        request = cast(models.AgentsRunsRequest, request)

        req = self._build_request_async(
            method="POST",
            path="/v1/agents/runs",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value=accept_header_override.value
            if accept_header_override is not None
            else "application/json;q=1, text/event-stream;q=0",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.AgentsRunsRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="AgentsRuns",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "422", "4XX", "5XX"],
            stream=True,
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            return unmarshal_json_response(
                models.AgentRunsBatchResponse, http_res, http_res_text
            )
        if utils.match_response(http_res, "200", "text/event-stream"):
            return eventstreaming.EventStreamAsync(
                http_res,
                lambda raw: utils.unmarshal_json(
                    raw, models.AgentRunsStreamingResponse
                ),
                client_ref=self,
            )
        if utils.match_response(http_res, "400", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            response_data = unmarshal_json_response(
                errors.AgentRuns400ResponseErrorData, http_res, http_res_text
            )
            raise errors.AgentRuns400ResponseError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "401", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            response_data = unmarshal_json_response(
                errors.AgentRuns401ResponseErrorData, http_res, http_res_text
            )
            raise errors.AgentRuns401ResponseError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "422", "application/json"):
            http_res_text = await utils.stream_to_text_async(http_res)
            response_data = unmarshal_json_response(
                errors.AgentRuns422ResponseErrorData, http_res, http_res_text
            )
            raise errors.AgentRuns422ResponseError(
                response_data, http_res, http_res_text
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)

        http_res_text = await utils.stream_to_text_async(http_res)
        raise errors.YouDefaultError(
            "Unexpected response received", http_res, http_res_text
        )
