"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from typing import Any, Mapping, Optional, Union
from youdotcom import errors, models, utils
from youdotcom._hooks import HookContext
from youdotcom.types import OptionalNullable, UNSET
from youdotcom.utils import get_security_from_env
from youdotcom.utils.unmarshal_json_response import unmarshal_json_response


class Search(BaseSDK):
    def unified(
        self,
        *,
        query: str = "Your query",
        count: Optional[int] = None,
        freshness: Optional[
            Union[models.SearchFreshness, models.SearchFreshnessTypedDict]
        ] = None,
        offset: Optional[int] = None,
        country: Optional[
            Union[models.SearchCountry, models.SearchCountryTypedDict]
        ] = None,
        language: Optional[models.Language] = models.Language.EN,
        safesearch: Optional[
            Union[models.SearchSafesearch, models.SearchSafesearchTypedDict]
        ] = None,
        livecrawl: Optional[
            Union[models.SearchLivecrawl, models.SearchLivecrawlTypedDict]
        ] = None,
        livecrawl_formats: Optional[
            Union[models.SearchLivecrawlFormats, models.SearchLivecrawlFormatsTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SearchResponse:
        r"""Returns a list of unified search results from web and news sources

        :param query: The search query used to retrieve relevant results from the web. You can also include [search operators](https://docs.you.com/search/search-operators) to refine your search.
        :param count: Specifies the maximum number of search results to return per section (the sections are `web` and `news`. See the JSON response to visualize them).
        :param freshness: Specifies the freshness of the results to return.
        :param offset: Indicates the `offset` for pagination. The `offset` is calculated in multiples of `count`. For example, if `count = 5` and `offset = 1`, results 5–10 will be returned. Range `0 ≤ offset ≤ 9`.
        :param country: The country code that determines the geographical focus of the web results.
        :param language: The language of the web results that will be returned (BCP 47 format).
        :param safesearch: Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not.
        :param livecrawl: Indicates which section(s) of search results to livecrawl and return full page content.
        :param livecrawl_formats: Indicates the format of the livecrawled content.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.SEARCH_OP_SERVERS[0]

        request = models.SearchRequest(
            query=query,
            count=count,
            freshness=freshness,
            offset=offset,
            country=country,
            language=language,
            safesearch=safesearch,
            livecrawl=livecrawl,
            livecrawl_formats=livecrawl_formats,
        )

        req = self._build_request(
            method="GET",
            path="/v1/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="search",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.SearchResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchUnauthorizedErrorData, http_res
            )
            raise errors.SearchUnauthorizedError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchForbiddenErrorData, http_res
            )
            raise errors.SearchForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchInternalServerErrorData, http_res
            )
            raise errors.SearchInternalServerError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)

        raise errors.YouDefaultError("Unexpected response received", http_res)

    async def unified_async(
        self,
        *,
        query: str = "Your query",
        count: Optional[int] = None,
        freshness: Optional[
            Union[models.SearchFreshness, models.SearchFreshnessTypedDict]
        ] = None,
        offset: Optional[int] = None,
        country: Optional[
            Union[models.SearchCountry, models.SearchCountryTypedDict]
        ] = None,
        language: Optional[models.Language] = models.Language.EN,
        safesearch: Optional[
            Union[models.SearchSafesearch, models.SearchSafesearchTypedDict]
        ] = None,
        livecrawl: Optional[
            Union[models.SearchLivecrawl, models.SearchLivecrawlTypedDict]
        ] = None,
        livecrawl_formats: Optional[
            Union[models.SearchLivecrawlFormats, models.SearchLivecrawlFormatsTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SearchResponse:
        r"""Returns a list of unified search results from web and news sources

        :param query: The search query used to retrieve relevant results from the web. You can also include [search operators](https://docs.you.com/search/search-operators) to refine your search.
        :param count: Specifies the maximum number of search results to return per section (the sections are `web` and `news`. See the JSON response to visualize them).
        :param freshness: Specifies the freshness of the results to return.
        :param offset: Indicates the `offset` for pagination. The `offset` is calculated in multiples of `count`. For example, if `count = 5` and `offset = 1`, results 5–10 will be returned. Range `0 ≤ offset ≤ 9`.
        :param country: The country code that determines the geographical focus of the web results.
        :param language: The language of the web results that will be returned (BCP 47 format).
        :param safesearch: Configures the safesearch filter for content moderation. This allows you to decide whether to return NSFW content or not.
        :param livecrawl: Indicates which section(s) of search results to livecrawl and return full page content.
        :param livecrawl_formats: Indicates the format of the livecrawled content.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.SEARCH_OP_SERVERS[0]

        request = models.SearchRequest(
            query=query,
            count=count,
            freshness=freshness,
            offset=offset,
            country=country,
            language=language,
            safesearch=safesearch,
            livecrawl=livecrawl,
            livecrawl_formats=livecrawl_formats,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="search",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["401", "403", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.SearchResponse, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchUnauthorizedErrorData, http_res
            )
            raise errors.SearchUnauthorizedError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchForbiddenErrorData, http_res
            )
            raise errors.SearchForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchInternalServerErrorData, http_res
            )
            raise errors.SearchInternalServerError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.YouDefaultError("API error occurred", http_res, http_res_text)

        raise errors.YouDefaultError("Unexpected response received", http_res)
