// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
)

// PostV1ContentsInternalServerError - Internal Server Error
type PostV1ContentsInternalServerError struct {
	Detail   *string                 `json:"detail,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostV1ContentsInternalServerError{}

func (e *PostV1ContentsInternalServerError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PostV1ContentsForbiddenError - Forbidden
type PostV1ContentsForbiddenError struct {
	Detail   *string                 `json:"detail,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostV1ContentsForbiddenError{}

func (e *PostV1ContentsForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PostV1ContentsUnauthorizedError - Unauthorized
type PostV1ContentsUnauthorizedError struct {
	// Error detail message.
	Detail   *string                 `json:"detail,omitempty"`
	HTTPMeta components.HTTPMetadata `json:"-"`
}

var _ error = &PostV1ContentsUnauthorizedError{}

func (e *PostV1ContentsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
