// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"mockserver/internal/sdk/models/components"
	"mockserver/internal/sdk/models/operations"
)

// PostV1AgentsRunsForbiddenError - Forbidden. API key lacks scope for this path.
type PostV1AgentsRunsForbiddenError struct {
	Errors   []operations.ForbiddenError `json:"errors"`
	HTTPMeta components.HTTPMetadata     `json:"-"`
}

var _ error = &PostV1AgentsRunsForbiddenError{}

func (e *PostV1AgentsRunsForbiddenError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// PostV1AgentsRunsUnauthorizedError - Unauthorized. Problems with API key.
type PostV1AgentsRunsUnauthorizedError struct {
	Errors   []operations.UnauthorizedError `json:"errors"`
	HTTPMeta components.HTTPMetadata        `json:"-"`
}

var _ error = &PostV1AgentsRunsUnauthorizedError{}

func (e *PostV1AgentsRunsUnauthorizedError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}

// BadRequestError - Bad Request. Invalid or malformed request body/parameters.
type BadRequestError struct {
	Errors   []operations.BadRequestError `json:"errors"`
	HTTPMeta components.HTTPMetadata      `json:"-"`
}

var _ error = &BadRequestError{}

func (e *BadRequestError) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
